AnalogIQ: CacheManager Class Reference
CacheManager Class Reference
Manages local caching of unit data and assets for the Analogiq plugin.
#include <CacheManager.h>
Public Member Functions
~CacheManager ()=default
Destructor.
CacheManager (const CacheManager &)=delete
CacheManager & operator= (const CacheManager &)=delete
bool initializeCache ()
Initializes the cache directory structure.
juce::File getCacheRoot () const
Gets the cache root directory.
bool isUnitCached (const juce::String &unitId) const
Checks if a unit JSON file is cached locally.
bool isFaceplateCached (const juce::String &unitId, const juce::String &filename) const
Checks if a faceplate image is cached locally.
bool isThumbnailCached (const juce::String &unitId, const juce::String &filename) const
Checks if a thumbnail image is cached locally.
bool isControlAssetCached (const juce::String &assetPath) const
Checks if a control asset is cached locally.
juce::File getCachedUnitPath (const juce::String &unitId) const
Gets the cached file path for a unit JSON.
juce::File getCachedFaceplatePath (const juce::String &unitId, const juce::String &filename) const
Gets the cached file path for a faceplate image.
juce::File getCachedThumbnailPath (const juce::String &unitId, const juce::String &filename) const
Gets the cached file path for a thumbnail image.
juce::File getCachedControlAssetPath (const juce::String &assetPath) const
Gets the cached file path for a control asset.
bool saveUnitToCache (const juce::String &unitId, const juce::String &jsonData)
Saves unit JSON data to the cache.
bool saveFaceplateToCache (const juce::String &unitId, const juce::String &filename, const juce::Image &image)
Saves a faceplate image to the cache.
bool saveThumbnailToCache (const juce::String &unitId, const juce::String &filename, const juce::Image &image)
Saves a thumbnail image to the cache.
bool saveControlAssetToCache (const juce::String &assetPath, const juce::MemoryBlock &imageData)
Saves a control asset to the cache.
juce::String loadUnitFromCache (const juce::String &unitId) const
Loads unit JSON data from the cache.
juce::Image loadFaceplateFromCache (const juce::String &unitId, const juce::String &filename) const
Loads a faceplate image from the cache.
juce::Image loadThumbnailFromCache (const juce::String &unitId, const juce::String &filename) const
Loads a thumbnail image from the cache.
juce::Image loadControlAssetFromCache (const juce::String &assetPath) const
Loads a control asset from the cache.
bool clearCache ()
Clears all cached data.
juce::int64 getCacheSize () const
Gets the total size of the cache in bytes.
bool addToRecentlyUsed (const juce::String &unitId)
Adds a gear item to the recently used list.
juce::StringArray getRecentlyUsed (int maxCount=MAX_RECENTLY_USED) const
Gets the list of recently used unit IDs.
bool removeFromRecentlyUsed (const juce::String &unitId)
Removes a unit from the recently used list.
bool clearRecentlyUsed ()
Clears the recently used list.
int getRecentlyUsedCount () const
Gets the number of items in the recently used list.
bool isRecentlyUsed (const juce::String &unitId) const
Checks if a unit is in the recently used list.
bool addToFavorites (const juce::String &unitId)
Adds a gear item to the favorites list.
juce::StringArray getFavorites () const
Gets the list of favorite unit IDs.
bool removeFromFavorites (const juce::String &unitId)
Removes a unit from the favorites list.
bool clearFavorites ()
Clears the favorites list.
int getFavoritesCount () const
Gets the number of items in the favorites list.
bool isFavorite (const juce::String &unitId) const
Checks if a unit is in the favorites list.
Static Public Member Functions
static CacheManager & getInstance ()
Gets the singleton instance of CacheManager.
Static Public Attributes
static constexpr int MAX_RECENTLY_USED = 20
Maximum number of recently used items that can be stored and displayed.
Private Member Functions
CacheManager ()
Private constructor for singleton pattern.
bool createDirectoryIfNeeded (const juce::File &directory) const
Creates a directory if it doesn't exist.
juce::File getUnitsDirectory () const
Gets the units directory.
juce::File getAssetsDirectory () const
Gets the assets directory.
juce::File getFaceplatesDirectory () const
Gets the faceplates directory.
juce::File getThumbnailsDirectory () const
Gets the thumbnails directory.
juce::File getControlsDirectory () const
Gets the controls directory.
juce::int64 calculateDirectorySize (const juce::File &directory) const
Calculates the total size of a directory recursively.
Private Attributes
juce::File cacheRoot
The cache root directory.
Detailed Description
Manages local caching of unit data and assets for the Analogiq plugin.
This singleton class handles caching of unit JSON definitions, faceplate images, thumbnails, and control assets to improve performance and enable offline usage. The cache is stored in the user's application data directory and mirrors the remote structure for consistency.
Definition at line 15 of file CacheManager.h.
Constructor & Destructor Documentation
~CacheManager()
CacheManager::~CacheManager () default
Destructor.
CacheManager() [1/2]
CacheManager::CacheManager (const CacheManager &) delete
References CacheManager().
Referenced by CacheManager(), getInstance(), and operator=().
CacheManager() [2/2]
CacheManager::CacheManager () private
Private constructor for singleton pattern.
Definition at line 6 of file CacheManager.cpp.
References cacheRoot.
Member Function Documentation
addToFavorites()
bool CacheManager::addToFavorites (const juce::String & unitId)
Adds a gear item to the favorites list.
Parameters
unitId The unit identifier to add to favorites
Returns
true if the operation was successful, false otherwise
Definition at line 601 of file CacheManager.cpp.
References cacheRoot.
Referenced by GearTreeItem::itemClicked().
addToRecentlyUsed()
bool CacheManager::addToRecentlyUsed (const juce::String & unitId)
Adds a gear item to the recently used list.
Parameters
unitId The unit identifier to add to recently used
Returns
true if the operation was successful, false otherwise
Definition at line 393 of file CacheManager.cpp.
References cacheRoot, and MAX_RECENTLY_USED.
Referenced by Rack::itemDropped().
calculateDirectorySize()
juce::int64 CacheManager::calculateDirectorySize (const juce::File & directory) const private
Calculates the total size of a directory recursively.
Parameters
directory The directory to calculate size for
Returns
The total size in bytes
Definition at line 325 of file CacheManager.cpp.
References calculateDirectorySize().
Referenced by calculateDirectorySize(), and getCacheSize().
clearCache()
bool CacheManager::clearCache ()
Clears all cached data.
Removes all files from the cache directory.
Returns
true if clearing was successful, false otherwise
Definition at line 291 of file CacheManager.cpp.
References cacheRoot.
clearFavorites()
bool CacheManager::clearFavorites ()
Clears the favorites list.
Returns
true if the operation was successful, false otherwise
Definition at line 723 of file CacheManager.cpp.
References cacheRoot.
Referenced by GearLibrary::clearFavorites().
clearRecentlyUsed()
bool CacheManager::clearRecentlyUsed ()
Clears the recently used list.
Returns
true if the operation was successful, false otherwise
Definition at line 527 of file CacheManager.cpp.
References cacheRoot.
Referenced by GearLibrary::clearRecentlyUsed().
createDirectoryIfNeeded()
bool CacheManager::createDirectoryIfNeeded (const juce::File & directory) const private
Creates a directory if it doesn't exist.
Parameters
directory The directory to create
Returns
true if creation was successful or directory already exists, false otherwise
Definition at line 350 of file CacheManager.cpp.
Referenced by initializeCache(), saveControlAssetToCache(), saveFaceplateToCache(), saveThumbnailToCache(), and saveUnitToCache().
getAssetsDirectory()
juce::File CacheManager::getAssetsDirectory () const private
Gets the assets directory.
Returns
The assets directory
Definition at line 372 of file CacheManager.cpp.
References cacheRoot.
Referenced by getControlsDirectory(), getFaceplatesDirectory(), getThumbnailsDirectory(), and initializeCache().
getCachedControlAssetPath()
juce::File CacheManager::getCachedControlAssetPath (const juce::String & assetPath) const
Gets the cached file path for a control asset.
Parameters
assetPath The relative path to the control asset
Returns
The cached file path, or empty string if not cached
Definition at line 107 of file CacheManager.cpp.
References getControlsDirectory().
Referenced by isControlAssetCached(), loadControlAssetFromCache(), and saveControlAssetToCache().
getCachedFaceplatePath()
juce::File CacheManager::getCachedFaceplatePath (const juce::String & unitId, const juce::String & filename) const
Gets the cached file path for a faceplate image.
Parameters
unitId The unit identifier
filename The faceplate filename (e.g., "la2a-compressor-1.0.0.jpg")
Returns
The cached file path, or empty string if not cached
Definition at line 97 of file CacheManager.cpp.
References getFaceplatesDirectory().
Referenced by isFaceplateCached(), loadFaceplateFromCache(), and saveFaceplateToCache().
getCachedThumbnailPath()
juce::File CacheManager::getCachedThumbnailPath (const juce::String & unitId, const juce::String & filename) const
Gets the cached file path for a thumbnail image.
Parameters
unitId The unit identifier
filename The thumbnail filename (e.g., "la2a-compressor-1.0.0.jpg")
Returns
The cached file path, or empty string if not cached
Definition at line 102 of file CacheManager.cpp.
References getThumbnailsDirectory().
Referenced by isThumbnailCached(), loadThumbnailFromCache(), and saveThumbnailToCache().
getCachedUnitPath()
juce::File CacheManager::getCachedUnitPath (const juce::String & unitId) const
Gets the cached file path for a unit JSON.
Parameters
unitId The unit identifier
Returns
The cached file path, or empty string if not cached
Definition at line 92 of file CacheManager.cpp.
References getUnitsDirectory().
Referenced by isUnitCached(), loadUnitFromCache(), and saveUnitToCache().
getCacheRoot()
juce::File CacheManager::getCacheRoot () const
Gets the cache root directory.
Returns
The cache root directory as a JUCE File object
Definition at line 63 of file CacheManager.cpp.
References cacheRoot.
getCacheSize()
juce::int64 CacheManager::getCacheSize () const
Gets the total size of the cache in bytes.
Returns
The total cache size in bytes
Definition at line 308 of file CacheManager.cpp.
References cacheRoot, and calculateDirectorySize().
getControlsDirectory()
juce::File CacheManager::getControlsDirectory () const private
Gets the controls directory.
Returns
The controls directory
Definition at line 387 of file CacheManager.cpp.
References getAssetsDirectory().
Referenced by getCachedControlAssetPath(), and initializeCache().
getFaceplatesDirectory()
juce::File CacheManager::getFaceplatesDirectory () const private
Gets the faceplates directory.
Returns
The faceplates directory
Definition at line 377 of file CacheManager.cpp.
References getAssetsDirectory().
Referenced by getCachedFaceplatePath(), initializeCache(), and saveFaceplateToCache().
getFavorites()
juce::StringArray CacheManager::getFavorites () const
Gets the list of favorite unit IDs.
Returns
Array of favorite unit IDs
Definition at line 645 of file CacheManager.cpp.
References cacheRoot.
Referenced by GearTreeItem::refreshSubItems(), and GearLibrary::updateFilteredItems().
getFavoritesCount()
int CacheManager::getFavoritesCount () const
Gets the number of items in the favorites list.
Returns
The number of favorite items
Definition at line 742 of file CacheManager.cpp.
References cacheRoot.
getInstance()
CacheManager & CacheManager::getInstance () static
Gets the singleton instance of CacheManager.
Returns
Reference to the CacheManager instance
Definition at line 13 of file CacheManager.cpp.
References CacheManager().
Referenced by GearLibrary::clearFavorites(), GearLibrary::clearRecentlyUsed(), Rack::fetchButtonSpriteSheet(), Rack::fetchFaceplateImage(), Rack::fetchFaderImage(), Rack::fetchKnobImage(), Rack::fetchSchemaForGearItem(), Rack::fetchSwitchSpriteSheet(), GearTreeItem::itemClicked(), Rack::itemDropped(), GearItem::loadImage(), GearTreeItem::paintItem(), GearTreeItem::refreshSubItems(), and GearLibrary::updateFilteredItems().
getRecentlyUsed()
juce::StringArray CacheManager::getRecentlyUsed (int maxCount = MAX_RECENTLY_USED) const
Gets the list of recently used unit IDs.
Parameters
maxCount Maximum number of items to return (default: MAX_RECENTLY_USED)
Returns
Array of recently used unit IDs, most recent first
Definition at line 443 of file CacheManager.cpp.
References cacheRoot.
Referenced by GearTreeItem::refreshSubItems(), and GearLibrary::updateFilteredItems().
getRecentlyUsedCount()
int CacheManager::getRecentlyUsedCount () const
Gets the number of items in the recently used list.
Returns
The number of recently used items
Definition at line 546 of file CacheManager.cpp.
References cacheRoot.
getThumbnailsDirectory()
juce::File CacheManager::getThumbnailsDirectory () const private
Gets the thumbnails directory.
Returns
The thumbnails directory
Definition at line 382 of file CacheManager.cpp.
References getAssetsDirectory().
Referenced by getCachedThumbnailPath(), initializeCache(), and saveThumbnailToCache().
getUnitsDirectory()
juce::File CacheManager::getUnitsDirectory () const private
Gets the units directory.
Returns
The units directory
Definition at line 367 of file CacheManager.cpp.
References cacheRoot.
Referenced by getCachedUnitPath(), initializeCache(), and saveUnitToCache().
initializeCache()
bool CacheManager::initializeCache ()
Initializes the cache directory structure.
Creates the cache root directory and all necessary subdirectories if they don't already exist.
Returns
true if initialization was successful, false otherwise
Definition at line 19 of file CacheManager.cpp.
References cacheRoot, createDirectoryIfNeeded(), getAssetsDirectory(), getControlsDirectory(), getFaceplatesDirectory(), getThumbnailsDirectory(), and getUnitsDirectory().
isControlAssetCached()
bool CacheManager::isControlAssetCached (const juce::String & assetPath) const
Checks if a control asset is cached locally.
Parameters
assetPath The relative path to the control asset (e.g., "knobs/bakelite-lg-black.png")
Returns
true if the control asset is cached, false otherwise
Definition at line 86 of file CacheManager.cpp.
References getCachedControlAssetPath().
Referenced by Rack::fetchButtonSpriteSheet(), Rack::fetchFaderImage(), Rack::fetchKnobImage(), and Rack::fetchSwitchSpriteSheet().
isFaceplateCached()
bool CacheManager::isFaceplateCached (const juce::String & unitId, const juce::String & filename) const
Checks if a faceplate image is cached locally.
Parameters
unitId The unit identifier
filename The faceplate filename (e.g., "la2a-compressor-1.0.0.jpg")
Returns
true if the faceplate image is cached, false otherwise
Definition at line 74 of file CacheManager.cpp.
References getCachedFaceplatePath().
Referenced by Rack::fetchFaceplateImage().
isFavorite()
bool CacheManager::isFavorite (const juce::String & unitId) const
Checks if a unit is in the favorites list.
Parameters
unitId The unit identifier to check
Returns
true if the unit is in the favorites list, false otherwise
Definition at line 766 of file CacheManager.cpp.
References cacheRoot.
Referenced by GearTreeItem::itemClicked(), and GearTreeItem::paintItem().
isRecentlyUsed()
bool CacheManager::isRecentlyUsed (const juce::String & unitId) const
Checks if a unit is in the recently used list.
Parameters
unitId The unit identifier to check
Returns
true if the unit is in the recently used list, false otherwise
Definition at line 570 of file CacheManager.cpp.
References cacheRoot.
isThumbnailCached()
bool CacheManager::isThumbnailCached (const juce::String & unitId, const juce::String & filename) const
Checks if a thumbnail image is cached locally.
Parameters
unitId The unit identifier
filename The thumbnail filename (e.g., "la2a-compressor-1.0.0.jpg")
Returns
true if the thumbnail image is cached, false otherwise
Definition at line 80 of file CacheManager.cpp.
References getCachedThumbnailPath().
Referenced by GearItem::loadImage().
isUnitCached()
bool CacheManager::isUnitCached (const juce::String & unitId) const
Checks if a unit JSON file is cached locally.
Parameters
unitId The unit identifier (e.g., "la2a-compressor-1.0.0")
Returns
true if the unit JSON is cached, false otherwise
Definition at line 68 of file CacheManager.cpp.
References getCachedUnitPath().
Referenced by Rack::fetchSchemaForGearItem().
loadControlAssetFromCache()
juce::Image CacheManager::loadControlAssetFromCache (const juce::String & assetPath) const
Loads a control asset from the cache.
Parameters
assetPath The relative path to the control asset
Returns
The cached image, or invalid image if not found
Definition at line 271 of file CacheManager.cpp.
References getCachedControlAssetPath().
Referenced by Rack::fetchButtonSpriteSheet(), Rack::fetchFaderImage(), Rack::fetchKnobImage(), and Rack::fetchSwitchSpriteSheet().
loadFaceplateFromCache()
juce::Image CacheManager::loadFaceplateFromCache (const juce::String & unitId, const juce::String & filename) const
Loads a faceplate image from the cache.
Parameters
unitId The unit identifier
filename The faceplate filename (e.g., "la2a-compressor-1.0.0.jpg")
Returns
The cached image, or invalid image if not found
Definition at line 231 of file CacheManager.cpp.
References getCachedFaceplatePath().
Referenced by Rack::fetchFaceplateImage().
loadThumbnailFromCache()
juce::Image CacheManager::loadThumbnailFromCache (const juce::String & unitId, const juce::String & filename) const
Loads a thumbnail image from the cache.
Parameters
unitId The unit identifier
filename The thumbnail filename (e.g., "la2a-compressor-1.0.0.jpg")
Returns
The cached image, or invalid image if not found
Definition at line 251 of file CacheManager.cpp.
References getCachedThumbnailPath().
Referenced by GearItem::loadImage().
loadUnitFromCache()
juce::String CacheManager::loadUnitFromCache (const juce::String & unitId) const
Loads unit JSON data from the cache.
Parameters
unitId The unit identifier
Returns
The cached JSON data, or empty string if not found
Definition at line 212 of file CacheManager.cpp.
References getCachedUnitPath().
Referenced by Rack::fetchSchemaForGearItem().
operator=()
CacheManager & CacheManager::operator= (const CacheManager &) delete
References CacheManager(), and MAX_RECENTLY_USED.
removeFromFavorites()
bool CacheManager::removeFromFavorites (const juce::String & unitId)
Removes a unit from the favorites list.
Parameters
unitId The unit identifier to remove
Returns
true if the operation was successful, false otherwise
Definition at line 673 of file CacheManager.cpp.
References cacheRoot.
Referenced by GearTreeItem::itemClicked().
removeFromRecentlyUsed()
bool CacheManager::removeFromRecentlyUsed (const juce::String & unitId)
Removes a unit from the recently used list.
Parameters
unitId The unit identifier to remove
Returns
true if the operation was successful, false otherwise
Definition at line 477 of file CacheManager.cpp.
References cacheRoot.
saveControlAssetToCache()
bool CacheManager::saveControlAssetToCache (const juce::String & assetPath, const juce::MemoryBlock & imageData)
Saves a control asset to the cache.
Parameters
assetPath The relative path to the control asset
imageData The image data to cache
Returns
true if saving was successful, false otherwise
Definition at line 185 of file CacheManager.cpp.
References createDirectoryIfNeeded(), and getCachedControlAssetPath().
Referenced by Rack::fetchButtonSpriteSheet(), Rack::fetchFaderImage(), Rack::fetchKnobImage(), and Rack::fetchSwitchSpriteSheet().
saveFaceplateToCache()
bool CacheManager::saveFaceplateToCache (const juce::String & unitId, const juce::String & filename, const juce::Image & image)
Saves a faceplate image to the cache.
Parameters
unitId The unit identifier
filename The faceplate filename (e.g., "la2a-compressor-1.0.0.jpg")
image The image to cache
Returns
true if saving was successful, false otherwise
Definition at line 131 of file CacheManager.cpp.
References createDirectoryIfNeeded(), getCachedFaceplatePath(), and getFaceplatesDirectory().
Referenced by Rack::fetchFaceplateImage().
saveThumbnailToCache()
bool CacheManager::saveThumbnailToCache (const juce::String & unitId, const juce::String & filename, const juce::Image & image)
Saves a thumbnail image to the cache.
Parameters
unitId The unit identifier
filename The thumbnail filename (e.g., "la2a-compressor-1.0.0.jpg")
image The image to cache
Returns
true if saving was successful, false otherwise
Definition at line 158 of file CacheManager.cpp.
References createDirectoryIfNeeded(), getCachedThumbnailPath(), and getThumbnailsDirectory().
Referenced by GearItem::loadImage().
saveUnitToCache()
bool CacheManager::saveUnitToCache (const juce::String & unitId, const juce::String & jsonData)
Saves unit JSON data to the cache.
Parameters
unitId The unit identifier
jsonData The JSON data to cache
Returns
true if saving was successful, false otherwise
Definition at line 112 of file CacheManager.cpp.
References createDirectoryIfNeeded(), getCachedUnitPath(), and getUnitsDirectory().
Referenced by Rack::fetchSchemaForGearItem().
Member Data Documentation
cacheRoot
juce::File CacheManager::cacheRoot private
The cache root directory.
Definition at line 362 of file CacheManager.h.
Referenced by addToFavorites(), addToRecentlyUsed(), CacheManager(), clearCache(), clearFavorites(), clearRecentlyUsed(), getAssetsDirectory(), getCacheRoot(), getCacheSize(), getFavorites(), getFavoritesCount(), getRecentlyUsed(), getRecentlyUsedCount(), getUnitsDirectory(), initializeCache(), isFavorite(), isRecentlyUsed(), removeFromFavorites(), and removeFromRecentlyUsed().
MAX_RECENTLY_USED
int CacheManager::MAX_RECENTLY_USED = 20 static constexpr
Maximum number of recently used items that can be stored and displayed.
Definition at line 21 of file CacheManager.h.
Referenced by addToRecentlyUsed(), operator=(), and GearTreeItem::refreshSubItems().
The documentation for this class was generated from the following files:
Source/CacheManager.h
Source/CacheManager.cpp