AnalogIQ: Rack Class Reference
Rack Class Reference
A component that manages a virtual rack of audio gear items.
#include <Rack.h>
Classes
class RackContainer
Internal container class for rack slots.
Public Member Functions
Rack (INetworkFetcher &networkFetcher, IFileSystem &fileSystem, CacheManager &cacheManager, PresetManager &presetManager, GearLibrary *gearLibrary)
Constructs a new Rack instance.
~Rack () override
Destructor for the Rack class.
void paint (juce::Graphics &g) override
Paints the rack's background.
void resized () override
Handles resizing of the rack component.
bool isInterestedInDragSource (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Checks if the rack is interested in a drag source.
void itemDragEnter (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Handles when a dragged item enters the rack.
void itemDragMove (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Handles when a dragged item moves over the rack.
void itemDragExit (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Handles when a dragged item exits the rack.
void itemDropped (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Handles when a dragged item is dropped onto the rack.
void rearrangeGearAsSortableList (int sourceSlotIndex, int targetSlotIndex)
Rearranges gear items in the rack using a sortable list.
RackSlot * findNearestSlot (const juce::Point< int > &position)
Finds the nearest rack slot to a given position.
int getNumSlots () const
Gets the number of slots in the rack.
RackSlot * getSlot (int index) const
Gets a specific slot by index.
void setGearLibrary (GearLibrary *library)
Sets the gear library reference.
void addRackStateListener (RackStateListener *listener)
Adds a listener for rack state changes.
void removeRackStateListener (RackStateListener *listener)
Removes a listener for rack state changes.
void notifyGearItemAdded (int slotIndex, GearItem *gearItem)
Notifies all listeners of a gear item being added.
void notifyGearItemRemoved (int slotIndex)
Notifies all listeners of a gear item being removed.
void notifyGearControlChanged (int slotIndex, GearItem *gearItem, int controlIndex)
Notifies all listeners of a gear control being changed.
void notifyGearItemsRearranged (int sourceSlotIndex, int targetSlotIndex)
Notifies all listeners of gear items being rearranged.
void notifyRackStateReset ()
Notifies all listeners of the rack state being reset.
void notifyPresetLoaded (const juce::String &presetName)
Notifies all listeners of a preset being loaded.
void notifyPresetSaved (const juce::String &presetName)
Notifies all listeners of a preset being saved.
void fetchSchemaForGearItem (GearItem *item, std::function< void()> onComplete=nullptr)
Fetches the schema for a gear item.
void parseSchema (const juce::String &schemaData, GearItem *item, std::function< void()> onComplete=nullptr)
Parses the schema data for a gear item.
void fetchFaceplateImage (GearItem *item)
Fetches the faceplate image for a gear item.
void fetchKnobImage (GearItem *item, int controlIndex)
Fetches the knob image for a gear control.
void fetchFaderImage (GearItem *item, int controlIndex)
Fetches the fader image for a gear control.
void fetchSwitchSpriteSheet (GearItem *item, int controlIndex)
Fetches the switch sprite sheet for a gear control.
void fetchButtonSpriteSheet (GearItem *item, int controlIndex)
Fetches the button sprite sheet for a gear control.
void createInstance (int slotIndex)
Creates a new instance of a gear item in a slot.
void resetToSource (int slotIndex)
Resets a slot to its source gear item.
bool isInstance (int slotIndex) const
Checks if a slot contains an instance.
juce::String getInstanceId (int slotIndex) const
Gets the instance ID for a slot.
void resetAllInstances ()
Resets all instances in the rack to their source gear items.
Private Member Functions
int getSlotHeight (int slotIndex) const
Gets the height of a specific rack slot.
int getDefaultSlotHeight () const
Gets the default height for a slot.
Rack (const Rack &)=delete
Rack & operator= (const Rack &)=delete
Private Attributes
int numSlots = 16
Number of slots in the rack.
int slotSpacing = 10
Spacing between slots in pixels.
std::unique_ptr< juce::Viewport > rackViewport
Viewport for scrolling the rack.
std::unique_ptr< RackContainer > rackContainer
Container for rack slots.
juce::OwnedArray< RackSlot > slots
Array of rack slots.
GearLibrary * gearLibrary
Pointer to the gear library.
INetworkFetcher & networkFetcher
Reference to the network fetcher.
IFileSystem & fileSystem
CacheManager & cacheManager
PresetManager & presetManager
juce::Array< RackStateListener * > rackStateListeners
Array of rack state listeners.
Detailed Description
A component that manages a virtual rack of audio gear items.
The Rack class provides a visual interface for managing audio gear items in a virtual rack. It handles the layout of gear items, drag-and-drop functionality for adding and rearranging items, and manages the loading and display of gear resources like faceplates and controls.
Definition at line 29 of file Rack.h.
Constructor & Destructor Documentation
Rack() [1/2]
Rack::Rack (INetworkFetcher & networkFetcher, IFileSystem & fileSystem, CacheManager & cacheManager, PresetManager & presetManager, GearLibrary * gearLibrary)
Constructs a new Rack instance.
Parameters
networkFetcher Reference to the network fetcher
fileSystem Reference to the file system
cacheManager Reference to the cache manager
presetManager Reference to the preset manager
gearLibrary Pointer to the gear library
Initializes the rack with a viewport and container, creates the specified number of rack slots, and sets up drag-and-drop functionality.
Definition at line 21 of file Rack.cpp.
References cacheManager, fileSystem, gearLibrary, networkFetcher, numSlots, presetManager, rackContainer, rackViewport, and slots.
Referenced by fetchButtonSpriteSheet(), fetchFaceplateImage(), fetchFaderImage(), fetchKnobImage(), fetchSchemaForGearItem(), fetchSwitchSpriteSheet(), and operator=().
~Rack()
Rack::~Rack () override
Destructor for the Rack class.
Cleans up resources and ensures all images are properly released.
Definition at line 52 of file Rack.cpp.
References GearItem::controls, GearItem::faceplateImage, GearItem::image, and slots.
Rack() [2/2]
Rack::Rack (const Rack &) private delete
Member Function Documentation
addRackStateListener()
void Rack::addRackStateListener (RackStateListener * listener)
Adds a listener for rack state changes.
Parameters
listener Pointer to the listener to add
Definition at line 2088 of file Rack.cpp.
References rackStateListeners.
createInstance()
void Rack::createInstance (int slotIndex)
Creates a new instance of a gear item in a slot.
Parameters
slotIndex The index of the slot to create the instance in
Definition at line 2020 of file Rack.cpp.
References getSlot().
fetchButtonSpriteSheet()
void Rack::fetchButtonSpriteSheet (GearItem * item, int controlIndex)
Fetches the button sprite sheet for a gear control.
Parameters
item The gear item containing the control
controlIndex The index of the control
Thread for downloading button sprite sheets.
This struct handles the asynchronous download and processing of button sprite sheets for gear controls, ensuring UI updates happen on the message thread.
Constructs a new ButtonSpriteSheetDownloader.
Parameters
urlToUse The URL to download the sprite sheet from
itemToUpdate The gear item containing the control
controlIndexToUpdate The index of the control to update
parentRack The rack to notify when the sprite sheet is loaded
assetPathToCache The asset path to use for caching
Destructor for ButtonSpriteSheetDownloader.
Ensures the thread is properly stopped before destruction.
Main thread execution function.
Downloads the button sprite sheet and updates the UI on the message thread.
< The URL to download from
< The gear item containing the control
< The index of the control to update
< The rack to notify
< The ID of the control being updated
< The name of the control being updated
< The asset path to use for caching
< Reference to cache manager
Definition at line 1789 of file Rack.cpp.
References GearControl::buttonSpriteSheet, cacheManager, GearItem::controls, GearLibrary::getFullUrl(), RackSlot::getGearItem(), getNumSlots(), getSlot(), GearControl::id, GearControl::image, and Rack().
Referenced by parseSchema().
fetchFaceplateImage()
void Rack::fetchFaceplateImage (GearItem * item)
Fetches the faceplate image for a gear item.
Parameters
item The gear item to fetch the faceplate for
Thread for downloading faceplate images.
This struct handles the asynchronous download and processing of faceplate images for gear items, ensuring UI updates happen on the message thread.
Constructs a new FaceplateImageDownloader.
Parameters
urlToUse The URL to download the image from
itemToUpdate The gear item to update with the image
parentRack The rack to notify when the image is loaded
filenameToCache The filename to use for caching
Destructor for FaceplateImageDownloader.
Ensures the thread is properly stopped before destruction.
Main thread execution function.
Downloads the faceplate image and updates the UI on the message thread.
< The URL to download from
< The gear item to update
< The rack to notify
< The filename to use for caching
< Reference to cache manager
Definition at line 862 of file Rack.cpp.
References cacheManager, GearItem::faceplateImage, GearItem::faceplateImagePath, fileSystem, GearLibrary::getFullUrl(), RackSlot::getGearItem(), getNumSlots(), getSlot(), Rack(), resized(), and GearItem::unitId.
Referenced by parseSchema().
fetchFaderImage()
void Rack::fetchFaderImage (GearItem * item, int controlIndex)
Fetches the fader image for a gear control.
Parameters
item The gear item containing the control
controlIndex The index of the control
Thread for downloading fader images.
This struct handles the asynchronous download and processing of fader images for gear controls, ensuring UI updates happen on the message thread.
Constructs a new FaderImageDownloader.
Parameters
urlToUse The URL to download the image from
itemToUpdate The gear item containing the control
controlIndexToUpdate The index of the control to update
parentRack The rack to notify when the image is loaded
assetPathToCache The asset path to use for caching
Destructor for FaderImageDownloader.
Ensures the thread is properly stopped before destruction.
Main thread execution function.
Downloads the fader image and updates the UI on the message thread.
< The URL to download from
< The gear item containing the control
< The index of the control to update
< The rack to notify
< The ID of the control being updated
< The name of the control being updated
< The asset path to use for caching
< Reference to cache manager
Definition at line 1325 of file Rack.cpp.
References cacheManager, GearItem::controls, GearControl::faderImage, GearLibrary::getFullUrl(), RackSlot::getGearItem(), getNumSlots(), getSlot(), GearControl::id, GearControl::image, and Rack().
Referenced by parseSchema().
fetchKnobImage()
void Rack::fetchKnobImage (GearItem * item, int controlIndex)
Fetches the knob image for a gear control.
Parameters
item The gear item containing the control
controlIndex The index of the control
Thread for downloading knob images.
This struct handles the asynchronous download and processing of knob images for gear controls, ensuring UI updates happen on the message thread.
Constructs a new KnobImageDownloader.
Parameters
urlToUse The URL to download the image from
itemToUpdate The gear item containing the control
controlIndexToUpdate The index of the control to update
parentRack The rack to notify when the image is loaded
assetPathToCache The asset path to use for caching
Destructor for KnobImageDownloader.
Ensures the thread is properly stopped before destruction.
Main thread execution function.
Downloads the knob image and updates the UI on the message thread.
< The URL to download from
< The gear item containing the control
< The index of the control to update
< The rack to notify
< The ID of the control being updated
< The name of the control being updated
< The asset path to use for caching
< Reference to cache manager
Definition at line 1094 of file Rack.cpp.
References cacheManager, GearItem::controls, GearLibrary::getFullUrl(), RackSlot::getGearItem(), getNumSlots(), getSlot(), GearControl::id, GearControl::image, GearControl::loadedImage, and Rack().
Referenced by parseSchema().
fetchSchemaForGearItem()
void Rack::fetchSchemaForGearItem (GearItem * item, std::function< void()> onComplete = nullptr)
Fetches the schema for a gear item.
Parameters
item The gear item to fetch the schema for
onComplete Optional callback to execute when schema loading is complete
item The gear item to fetch the schema for
Thread for downloading and processing schema data.
This struct handles the asynchronous download and processing of schema data for gear items, ensuring UI updates happen on the message thread.
Constructs a new SchemaDownloader.
Parameters
urlToUse The URL to download the schema from
itemToUpdate The gear item to update with the schema
rackToNotify The rack to notify when the schema is loaded
unitIdToCache The unit ID to use for caching
onComplete Optional callback to execute when parsing is complete
Destructor for SchemaDownloader.
Ensures the thread is properly stopped before destruction.
Main thread execution function.
Downloads the schema data and processes it on the message thread.
< The URL to download from
< The gear item to update
< The rack to notify
< The downloaded schema data
< Whether the download was successful
< The unit ID to use for caching
< Reference to cache manager
< Optional completion callback
Definition at line 450 of file Rack.cpp.
References cacheManager, GearLibrary::getFullUrl(), parseSchema(), Rack(), GearItem::schemaPath, and GearItem::unitId.
Referenced by PresetManager::deserializeJSONToRack(), and itemDropped().
fetchSwitchSpriteSheet()
void Rack::fetchSwitchSpriteSheet (GearItem * item, int controlIndex)
Fetches the switch sprite sheet for a gear control.
Parameters
item The gear item containing the control
controlIndex The index of the control
Thread for downloading switch sprite sheets.
This struct handles the asynchronous download and processing of switch sprite sheets for gear controls, ensuring UI updates happen on the message thread.
Constructs a new SwitchSpriteSheetDownloader.
Parameters
urlToUse The URL to download the sprite sheet from
itemToUpdate The gear item containing the control
controlIndexToUpdate The index of the control to update
parentRack The rack to notify when the sprite sheet is loaded
assetPathToCache The asset path to use for caching
Destructor for SwitchSpriteSheetDownloader.
Ensures the thread is properly stopped before destruction.
Main thread execution function.
Downloads the switch sprite sheet and updates the UI on the message thread.
< The URL to download from
< The gear item containing the control
< The index of the control to update
< The rack to notify
< The ID of the control being updated
< The name of the control being updated
< The asset path to use for caching
< Reference to cache manager
Definition at line 1557 of file Rack.cpp.
References cacheManager, GearItem::controls, GearLibrary::getFullUrl(), RackSlot::getGearItem(), getNumSlots(), getSlot(), GearControl::id, GearControl::image, Rack(), and GearControl::switchSpriteSheet.
Referenced by parseSchema().
findNearestSlot()
RackSlot * Rack::findNearestSlot (const juce::Point< int > & position)
Finds the nearest rack slot to a given position.
Parameters
position The position to find the nearest slot for
Returns
Pointer to the nearest RackSlot, or nullptr if none found
Definition at line 409 of file Rack.cpp.
References rackContainer, and slots.
Referenced by itemDragMove(), and itemDropped().
getDefaultSlotHeight()
int Rack::getDefaultSlotHeight () const inline private
Gets the default height for a slot.
Returns
The default slot height in pixels
Definition at line 368 of file Rack.h.
Referenced by getSlotHeight().
getInstanceId()
juce::String Rack::getInstanceId (int slotIndex) const
Gets the instance ID for a slot.
Parameters
slotIndex The index of the slot
Returns
The instance ID as a string
Definition at line 2062 of file Rack.cpp.
References getSlot().
getNumSlots()
int Rack::getNumSlots () const inline
Gets the number of slots in the rack.
Returns
The number of slots
Definition at line 124 of file Rack.h.
References slots.
Referenced by PresetManager::deserializeJSONToRack(), fetchButtonSpriteSheet(), fetchFaceplateImage(), fetchFaderImage(), fetchKnobImage(), fetchSwitchSpriteSheet(), RackSlot::moveDown(), PresetManager::serializeRackToJSON(), and RackSlot::updateButtonStates().
getSlot()
RackSlot * Rack::getSlot (int index) const inline
Gets a specific slot by index.
Parameters
index The index of the slot to get
Returns
Pointer to the RackSlot, or nullptr if index is invalid
Definition at line 132 of file Rack.h.
References slots.
Referenced by createInstance(), PresetManager::deserializeJSONToRack(), fetchButtonSpriteSheet(), fetchFaceplateImage(), fetchFaderImage(), fetchKnobImage(), fetchSwitchSpriteSheet(), getInstanceId(), isInstance(), resetAllInstances(), resetToSource(), and PresetManager::serializeRackToJSON().
getSlotHeight()
int Rack::getSlotHeight (int slotIndex) const private
Gets the height of a specific rack slot.
Parameters
slotIndex The index of the slot to get the height for
Returns
The height of the slot in pixels
Definition at line 95 of file Rack.cpp.
References GearItem::faceplateImage, getDefaultSlotHeight(), RackSlot::getGearItem(), RackSlot::isAvailable(), rackContainer, slots, and slotSpacing.
Referenced by resized().
isInstance()
bool Rack::isInstance (int slotIndex) const
Checks if a slot contains an instance.
Parameters
slotIndex The index of the slot to check
Returns
true if the slot contains an instance
Definition at line 2047 of file Rack.cpp.
References getSlot().
isInterestedInDragSource()
bool Rack::isInterestedInDragSource (const juce::DragAndDropTarget::SourceDetails & dragSourceDetails) override
Checks if the rack is interested in a drag source.
Parameters
dragSourceDetails Details about the drag source
Returns
true if the rack accepts drops from this source
Definition at line 184 of file Rack.cpp.
itemDragEnter()
void Rack::itemDragEnter (const juce::DragAndDropTarget::SourceDetails & dragSourceDetails) override
Handles when a dragged item enters the rack.
Parameters
dragSourceDetails Details about the drag source
Definition at line 218 of file Rack.cpp.
itemDragExit()
void Rack::itemDragExit (const juce::DragAndDropTarget::SourceDetails & dragSourceDetails) override
Handles when a dragged item exits the rack.
Parameters
dragSourceDetails Details about the drag source
Definition at line 245 of file Rack.cpp.
References slots.
itemDragMove()
void Rack::itemDragMove (const juce::DragAndDropTarget::SourceDetails & details) override
Handles when a dragged item moves over the rack.
Parameters
dragSourceDetails Details about the drag source and position
details Details about the drag source and position
Definition at line 228 of file Rack.cpp.
References findNearestSlot(), and slots.
itemDropped()
void Rack::itemDropped (const juce::DragAndDropTarget::SourceDetails & details) override
Handles when a dragged item is dropped onto the rack.
Parameters
dragSourceDetails Details about the drag source and drop position
details Details about the drag source and drop position
Definition at line 259 of file Rack.cpp.
References cacheManager, fetchSchemaForGearItem(), fileSystem, findNearestSlot(), gearLibrary, RackSlot::getGearItem(), networkFetcher, RackSlot::setGearItem(), slots, and GearItem::unitId.
Referenced by RackSlot::itemDropped().
notifyGearControlChanged()
void Rack::notifyGearControlChanged (int slotIndex, GearItem * gearItem, int controlIndex)
Notifies all listeners of a gear control being changed.
Parameters
slotIndex The index of the slot that was modified
gearItem Pointer to the gear item that was modified
controlIndex The index of the control that was modified
Definition at line 2123 of file Rack.cpp.
References rackStateListeners.
Referenced by RackSlot::notifyRackOfControlChanged().
notifyGearItemAdded()
void Rack::notifyGearItemAdded (int slotIndex, GearItem * gearItem)
Notifies all listeners of a gear item being added.
Parameters
slotIndex The index of the slot that was modified
gearItem Pointer to the gear item that was added
Definition at line 2101 of file Rack.cpp.
References rackStateListeners.
Referenced by RackSlot::notifyRackOfGearItemAdded().
notifyGearItemRemoved()
void Rack::notifyGearItemRemoved (int slotIndex)
Notifies all listeners of a gear item being removed.
Parameters
slotIndex The index of the slot that was modified
Definition at line 2112 of file Rack.cpp.
References rackStateListeners.
Referenced by RackSlot::notifyRackOfGearItemRemoved().
notifyGearItemsRearranged()
void Rack::notifyGearItemsRearranged (int sourceSlotIndex, int targetSlotIndex)
Notifies all listeners of gear items being rearranged.
Parameters
sourceSlotIndex The index of the source slot
targetSlotIndex The index of the target slot
Definition at line 2134 of file Rack.cpp.
References rackStateListeners.
notifyPresetLoaded()
void Rack::notifyPresetLoaded (const juce::String & presetName)
Notifies all listeners of a preset being loaded.
Parameters
presetName The name of the preset that was loaded
Definition at line 2156 of file Rack.cpp.
References rackStateListeners.
notifyPresetSaved()
void Rack::notifyPresetSaved (const juce::String & presetName)
Notifies all listeners of a preset being saved.
Parameters
presetName The name of the preset that was saved
Definition at line 2167 of file Rack.cpp.
References rackStateListeners.
notifyRackStateReset()
void Rack::notifyRackStateReset ()
Notifies all listeners of the rack state being reset.
Definition at line 2145 of file Rack.cpp.
References rackStateListeners.
operator=()
Rack & Rack::operator= (const Rack &) private delete
References Rack().
paint()
void Rack::paint (juce::Graphics & g) override
Paints the rack's background.
Parameters
g The graphics context to paint with
Definition at line 84 of file Rack.cpp.
parseSchema()
void Rack::parseSchema (const juce::String & schemaData, GearItem * item, std::function< void()> onComplete = nullptr)
Parses the schema data for a gear item.
Parameters
schemaData The JSON schema data to parse
item The gear item to update with the parsed schema
onComplete Optional callback to execute when parsing is complete
Definition at line 571 of file Rack.cpp.
References GearControl::Button, GearControl::buttonFrames, GearItem::controls, GearControl::currentIndex, GearControl::currentStepIndex, GearControl::endAngle, GearItem::faceplateImagePath, GearControl::Fader, fetchButtonSpriteSheet(), fetchFaceplateImage(), fetchFaderImage(), fetchKnobImage(), fetchSwitchSpriteSheet(), GearControl::SwitchOptionFrame::height, GearControl::id, GearControl::image, GearControl::initialValue, GearControl::Knob, GearControl::SwitchOptionFrame::label, GearControl::length, GearControl::momentary, GearControl::options, GearControl::orientation, GearControl::startAngle, GearControl::steps, GearControl::Switch, GearControl::switchFrames, GearControl::type, GearControl::SwitchOptionFrame::value, GearControl::value, GearControl::SwitchOptionFrame::width, GearControl::SwitchOptionFrame::x, and GearControl::SwitchOptionFrame::y.
Referenced by fetchSchemaForGearItem().
rearrangeGearAsSortableList()
void Rack::rearrangeGearAsSortableList (int sourceSlotIndex, int targetSlotIndex)
Rearranges gear items in the rack using a sortable list.
Parameters
sourceSlotIndex The index of the source slot
targetSlotIndex The index of the target slot
Definition at line 356 of file Rack.cpp.
References RackSlot::clearGearItem(), RackSlot::getGearItem(), resized(), RackSlot::setGearItem(), and slots.
Referenced by RackSlot::moveDown(), and RackSlot::moveUp().
removeRackStateListener()
void Rack::removeRackStateListener (RackStateListener * listener)
Removes a listener for rack state changes.
Parameters
listener Pointer to the listener to remove
Definition at line 2096 of file Rack.cpp.
References rackStateListeners.
resetAllInstances()
void Rack::resetAllInstances ()
Resets all instances in the rack to their source gear items.
Definition at line 2074 of file Rack.cpp.
References getSlot(), and slots.
resetToSource()
void Rack::resetToSource (int slotIndex)
Resets a slot to its source gear item.
Parameters
slotIndex The index of the slot to reset
Definition at line 2033 of file Rack.cpp.
References getSlot().
resized()
void Rack::resized () override
Handles resizing of the rack component.
Adjusts the layout of the viewport, container, and all rack slots based on the new dimensions.
Definition at line 138 of file Rack.cpp.
References getSlotHeight(), rackContainer, rackViewport, slots, and slotSpacing.
Referenced by RackSlot::clearGearItem(), fetchFaceplateImage(), and rearrangeGearAsSortableList().
setGearLibrary()
void Rack::setGearLibrary (GearLibrary * library) inline
Sets the gear library reference.
Parameters
library Pointer to the GearLibrary instance
Definition at line 139 of file Rack.h.
References gearLibrary.
Member Data Documentation
cacheManager
CacheManager& Rack::cacheManager private
Definition at line 347 of file Rack.h.
Referenced by fetchButtonSpriteSheet(), fetchFaceplateImage(), fetchFaderImage(), fetchKnobImage(), fetchSchemaForGearItem(), fetchSwitchSpriteSheet(), itemDropped(), and Rack().
fileSystem
IFileSystem& Rack::fileSystem private
Definition at line 344 of file Rack.h.
Referenced by fetchFaceplateImage(), itemDropped(), and Rack().
gearLibrary
GearLibrary* Rack::gearLibrary private
Pointer to the gear library.
Definition at line 338 of file Rack.h.
Referenced by itemDropped(), Rack(), and setGearLibrary().
networkFetcher
INetworkFetcher& Rack::networkFetcher private
Reference to the network fetcher.
Definition at line 341 of file Rack.h.
Referenced by itemDropped(), and Rack().
numSlots
int Rack::numSlots = 16 private
Number of slots in the rack.
Definition at line 329 of file Rack.h.
Referenced by Rack().
presetManager
PresetManager& Rack::presetManager private
Definition at line 350 of file Rack.h.
Referenced by Rack().
rackContainer
std::unique_ptr<RackContainer> Rack::rackContainer private
Container for rack slots.
Definition at line 334 of file Rack.h.
Referenced by findNearestSlot(), getSlotHeight(), Rack(), and resized().
rackStateListeners
juce::Array<RackStateListener *> Rack::rackStateListeners private
Array of rack state listeners.
Definition at line 353 of file Rack.h.
Referenced by addRackStateListener(), notifyGearControlChanged(), notifyGearItemAdded(), notifyGearItemRemoved(), notifyGearItemsRearranged(), notifyPresetLoaded(), notifyPresetSaved(), notifyRackStateReset(), and removeRackStateListener().
rackViewport
std::unique_ptr<juce::Viewport> Rack::rackViewport private
Viewport for scrolling the rack.
Definition at line 333 of file Rack.h.
Referenced by Rack(), and resized().
slots
juce::OwnedArray<RackSlot> Rack::slots private
Array of rack slots.
Definition at line 335 of file Rack.h.
Referenced by findNearestSlot(), getNumSlots(), getSlot(), getSlotHeight(), itemDragExit(), itemDragMove(), itemDropped(), Rack(), rearrangeGearAsSortableList(), resetAllInstances(), resized(), and ~Rack().
slotSpacing
int Rack::slotSpacing = 10 private
Spacing between slots in pixels.
Definition at line 330 of file Rack.h.
Referenced by getSlotHeight(), and resized().
The documentation for this class was generated from the following files:
Source/Rack.h
Source/Rack.cpp