AnalogIQ: GearLibrary Class Reference
GearLibrary Class Reference
Main class for managing and displaying audio gear items.
#include <GearLibrary.h>
Public Member Functions
GearLibrary (INetworkFetcher &networkFetcher, IFileSystem &fileSystem, CacheManager &cacheManager, PresetManager &presetManager)
Constructor for GearLibrary.
~GearLibrary () override
Destructor for GearLibrary.
void paint (juce::Graphics &g) override
Paints the GearLibrary component.
void resized () override
Handles resizing of the GearLibrary component.
int getNumRows ()
Gets the number of rows in the gear list.
void paintListBoxItem (int rowNumber, juce::Graphics &g, int width, int height, bool rowIsSelected)
Paints a list box item.
juce::Component * refreshComponentForRow (int rowNumber, bool isRowSelected, juce::Component *existingComponentToUpdate)
Refreshes a component for a specific row in the list box.
void listBoxItemClicked (int row, const juce::MouseEvent &e)
Handles a list box item click.
void listBoxItemDoubleClicked (int row, const juce::MouseEvent &e)
Handles a list box item double click.
void mouseDown (const juce::MouseEvent &e) override
Handles mouse down events.
void mouseDrag (const juce::MouseEvent &e) override
Handles mouse drag events.
void buttonClicked (juce::Button *button) override
Handles button click events.
GearItem * getGearItem (int index)
Gets a gear item by index.
const juce::Array< GearItem > & getItems () const
Gets the full array of gear items.
CacheManager & getCacheManager ()
Gets the cache manager.
void loadLibraryAsync ()
Loads the gear library data asynchronously.
void loadGearItemsAsync ()
Loads gear items asynchronously.
void saveLibraryAsync ()
Saves the gear library data asynchronously.
void addItem (const juce::String &name, const juce::String &category, const juce::String &description, const juce::String &manufacturer)
Adds a new gear item to the library.
void updateFilteredItems ()
Updates the filtered items in both list and tree views.
void refreshTreeView ()
Refreshes the tree view to update recently used items.
void refreshRecentlyUsedSection ()
Refreshes only the recently used section of the tree.
void clearRecentlyUsed ()
Clears the recently used items and refreshes the tree view.
void refreshFavoritesSection ()
Refreshes only the favorites section of the tree.
void clearFavorites ()
Clears the favorites items and refreshes the tree view.
Static Public Member Functions
static juce::String getFullUrl (const juce::String &relativePath)
Constructs a full URL from a relative path.
Private Member Functions
void parseGearLibrary (const juce::String &jsonData)
Parses the gear library data from JSON format.
bool shouldShowItem (const GearItem &item) const
Determines if a gear item should be shown based on current search.
juce::String normalizeForSearch (const juce::String &text) const
Normalizes text for fuzzy search by removing ignored characters.
GearLibrary (const GearLibrary &)=delete
GearLibrary & operator= (const GearLibrary &)=delete
Static Private Member Functions
static juce::Array< juce::juce_wchar > getIgnoredCharacters ()
Gets the list of characters to ignore during search.
Private Attributes
juce::Label titleLabel {"titleLabel", "Gear Library"}
Title label for the library.
juce::DrawableButton refreshButton {"RefreshButton", juce::DrawableButton::ButtonStyle::ImageOnButtonBackground}
Button to refresh the gear list.
juce::TextEditor searchBox
Text box for searching gear items.
std::unique_ptr< GearListBoxModel > gearListModel
Model for the legacy list box.
std::unique_ptr< DraggableListBox > gearListBox
Legacy list box component.
std::unique_ptr< juce::TreeView > gearTreeView
Tree view for hierarchical display.
std::unique_ptr< GearTreeItem > rootItem
Root item of the tree view.
juce::Array< GearItem > gearItems
Array of all gear items.
juce::String currentSearchText
Current search text.
INetworkFetcher & networkFetcher
Reference to the network fetcher.
IFileSystem & fileSystem
Reference to the file system.
CacheManager & cacheManager
Reference to the cache manager.
PresetManager & presetManager
Reference to the preset manager.
Detailed Description
Main class for managing and displaying audio gear items.
The GearLibrary class provides a user interface for browsing, searching, and managing audio gear items. It supports both a legacy list view and a new hierarchical tree view.
Definition at line 45 of file GearLibrary.h.
Constructor & Destructor Documentation
GearLibrary() [1/2]
GearLibrary::GearLibrary (INetworkFetcher & networkFetcher, IFileSystem & fileSystem, CacheManager & cacheManager, PresetManager & presetManager)
Constructor for GearLibrary.
Constructs a new GearLibrary.
Parameters
networkFetcher The network fetcher to use for loading resources
fileSystem The file system to use for file operations
cacheManager The cache manager to use for file operations
presetManager The preset manager to use for preset operations
Initializes the UI components including the title label, search box, refresh button, add user gear button, and both list and tree views.
Definition at line 96 of file GearLibrary.cpp.
References cacheManager, currentSearchText, fileSystem, gearListBox, gearListModel, gearTreeView, networkFetcher, presetManager, refreshButton, GearTreeItem::Root, rootItem, searchBox, titleLabel, and updateFilteredItems().
Referenced by GearLibrary().
~GearLibrary()
GearLibrary::~GearLibrary () override
Destructor for GearLibrary.
Ensures proper cleanup of the tree view root item.
Definition at line 167 of file GearLibrary.cpp.
References gearTreeView.
GearLibrary() [2/2]
GearLibrary::GearLibrary (const GearLibrary &) private delete
References GearLibrary().
Member Function Documentation
addItem()
void GearLibrary::addItem (const juce::String & name, const juce::String & category, const juce::String & description, const juce::String & manufacturer)
Adds a new gear item to the library.
Parameters
name The name of the gear item
category The category of the gear item
description The description of the gear item
manufacturer The manufacturer of the gear item
Creates and adds a new gear item with the specified properties.
Parameters
name The name of the gear item
category The category of the gear item
description The description of the gear item
manufacturer The manufacturer of the gear item
Definition at line 1341 of file GearLibrary.cpp.
References cacheManager, Compressor, EQ, fileSystem, gearItems, networkFetcher, Other, Preamp, Rack19Inch, rootItem, and Series500.
buttonClicked()
void GearLibrary::buttonClicked (juce::Button * button) override
Handles button click events.
Parameters
button Pointer to the clicked button
Processes clicks on the refresh button.
Parameters
button Pointer to the clicked button
Definition at line 1394 of file GearLibrary.cpp.
References loadLibraryAsync(), and refreshButton.
clearFavorites()
void GearLibrary::clearFavorites ()
Clears the favorites items and refreshes the tree view.
This method clears all favorite items from the cache and updates the tree view display.
Definition at line 1010 of file GearLibrary.cpp.
References cacheManager, and refreshTreeView().
clearRecentlyUsed()
void GearLibrary::clearRecentlyUsed ()
Clears the recently used items and refreshes the tree view.
This method clears all recently used items from the cache and updates the tree view display.
Definition at line 726 of file GearLibrary.cpp.
References cacheManager, and refreshTreeView().
getCacheManager()
CacheManager & GearLibrary::getCacheManager () inline
Gets the cache manager.
Returns
Reference to the cache manager
Definition at line 161 of file GearLibrary.h.
References cacheManager.
getFullUrl()
juce::String GearLibrary::getFullUrl (const juce::String & relativePath) inline static
Constructs a full URL from a relative path.
Parameters
relativePath The relative path to convert
Returns
The full URL
Definition at line 194 of file GearLibrary.h.
References RemoteResources::ASSETS_PATH, RemoteResources::BASE_URL, and RemoteResources::SCHEMAS_PATH.
Referenced by Rack::fetchButtonSpriteSheet(), Rack::fetchFaceplateImage(), Rack::fetchFaderImage(), Rack::fetchKnobImage(), Rack::fetchSchemaForGearItem(), Rack::fetchSwitchSpriteSheet(), loadGearItemsAsync(), and GearItem::loadImage().
getGearItem()
GearItem * GearLibrary::getGearItem (int index)
Gets a gear item by index.
Parameters
index The index of the gear item to retrieve
Returns
Pointer to the gear item, or nullptr if index is invalid
Definition at line 1301 of file GearLibrary.cpp.
References gearItems.
getIgnoredCharacters()
juce::Array< juce::juce_wchar > GearLibrary::getIgnoredCharacters () static private
Gets the list of characters to ignore during search.
Returns
Array of characters that should be ignored during fuzzy matching
Definition at line 218 of file GearLibrary.cpp.
Referenced by normalizeForSearch().
getItems()
const juce::Array< GearItem > & GearLibrary::getItems () const inline
Gets the full array of gear items.
Returns
Constant reference to the array of gear items
Definition at line 154 of file GearLibrary.h.
References gearItems.
Referenced by PresetManager::deserializeJSONToRack().
getNumRows()
int GearLibrary::getNumRows ()
Gets the number of rows in the gear list.
Returns
The total number of gear items in the library
Definition at line 1021 of file GearLibrary.cpp.
References gearItems.
listBoxItemClicked()
void GearLibrary::listBoxItemClicked (int row, const juce::MouseEvent & e)
Handles a list box item click.
Parameters
row The index of the clicked row
e The mouse event details
Definition at line 1079 of file GearLibrary.cpp.
References gearListBox.
listBoxItemDoubleClicked()
void GearLibrary::listBoxItemDoubleClicked (int row, const juce::MouseEvent & e)
Handles a list box item double click.
Parameters
row The index of the double-clicked row
e The mouse event details
Definition at line 1092 of file GearLibrary.cpp.
loadGearItemsAsync()
void GearLibrary::loadGearItemsAsync ()
Loads gear items asynchronously.
Fetches gear items from a remote source or uses fallback data if the remote source is unavailable.
Definition at line 1114 of file GearLibrary.cpp.
References getFullUrl(), RemoteResources::LIBRARY_PATH, networkFetcher, and parseGearLibrary().
Referenced by loadLibraryAsync().
loadLibraryAsync()
void GearLibrary::loadLibraryAsync ()
Loads the gear library data asynchronously.
Initiates gear item loading operations.
Definition at line 1102 of file GearLibrary.cpp.
References loadGearItemsAsync().
Referenced by buttonClicked().
mouseDown()
void GearLibrary::mouseDown (const juce::MouseEvent & e) override
Handles mouse down events.
Parameters
e The mouse event details
Definition at line 1314 of file GearLibrary.cpp.
mouseDrag()
void GearLibrary::mouseDrag (const juce::MouseEvent & e) override
Handles mouse drag events.
Parameters
e The mouse event details
Definition at line 1325 of file GearLibrary.cpp.
normalizeForSearch()
juce::String GearLibrary::normalizeForSearch (const juce::String & text) const private
Normalizes text for fuzzy search by removing ignored characters.
Parameters
text The text to normalize
Returns
The normalized text (lowercase with ignored characters removed)
Definition at line 244 of file GearLibrary.cpp.
References getIgnoredCharacters().
Referenced by shouldShowItem().
operator=()
GearLibrary & GearLibrary::operator= (const GearLibrary &) private delete
paint()
void GearLibrary::paint (juce::Graphics & g) override
Paints the GearLibrary component.
Parameters
g The graphics context to paint with
Definition at line 178 of file GearLibrary.cpp.
paintListBoxItem()
void GearLibrary::paintListBoxItem (int rowNumber, juce::Graphics & g, int width, int height, bool rowIsSelected)
Paints a list box item.
Parameters
rowNumber The index of the row to paint
g The graphics context to paint with
width The width of the item
height The height of the item
rowIsSelected Whether the row is currently selected
Definition at line 1035 of file GearLibrary.cpp.
References gearItems.
parseGearLibrary()
void GearLibrary::parseGearLibrary (const juce::String & jsonData) private
Parses the gear library data from JSON format.
Parses the gear library JSON data.
Parameters
jsonData The JSON string containing gear library data
Processes JSON data containing gear items and populates the library. Supports both new and legacy JSON formats.
Parameters
jsonData The JSON string containing gear library data
Definition at line 1142 of file GearLibrary.cpp.
References RemoteResources::ASSETS_PATH, cacheManager, Compressor, EQ, fileSystem, gearItems, GearItem::loadImage(), networkFetcher, Other, Preamp, Rack19Inch, refreshFavoritesSection(), refreshRecentlyUsedSection(), rootItem, RemoteResources::SCHEMAS_PATH, Series500, and UserCreated.
Referenced by loadGearItemsAsync().
refreshComponentForRow()
juce::Component * GearLibrary::refreshComponentForRow (int rowNumber, bool isRowSelected, juce::Component * existingComponentToUpdate)
Refreshes a component for a specific row in the list box.
Parameters
rowNumber The index of the row to refresh
isRowSelected Whether the row is currently selected
existingComponentToUpdate The existing component to update, if any
Returns
The component to display for the row, or nullptr if using default painting
Definition at line 1067 of file GearLibrary.cpp.
refreshFavoritesSection()
void GearLibrary::refreshFavoritesSection ()
Refreshes only the favorites section of the tree.
This method updates only the favorite items without affecting the expansion state of other tree nodes.
Definition at line 738 of file GearLibrary.cpp.
References cacheManager, GearTreeItem::Category, Compressor, EQ, GearTreeItem::Favorites, GearTreeItem::Gear, gearItems, gearTreeView, Other, Preamp, and rootItem.
Referenced by parseGearLibrary(), and updateFilteredItems().
refreshRecentlyUsedSection()
void GearLibrary::refreshRecentlyUsedSection ()
Refreshes only the recently used section of the tree.
This method updates only the recently used items without affecting the expansion state of other tree nodes.
Definition at line 613 of file GearLibrary.cpp.
References cacheManager, GearTreeItem::Gear, gearItems, gearTreeView, GearTreeItem::RecentlyUsed, and rootItem.
Referenced by parseGearLibrary(), and updateFilteredItems().
refreshTreeView()
void GearLibrary::refreshTreeView ()
Refreshes the tree view to update recently used items.
This method should be called when recently used items change to update the tree view display.
Definition at line 597 of file GearLibrary.cpp.
References gearTreeView, and rootItem.
Referenced by clearFavorites(), and clearRecentlyUsed().
resized()
void GearLibrary::resized () override
Handles resizing of the GearLibrary component.
Updates the bounds of all child components based on the new size.
Definition at line 188 of file GearLibrary.cpp.
References gearListBox, gearTreeView, refreshButton, searchBox, and titleLabel.
saveLibraryAsync()
void GearLibrary::saveLibraryAsync ()
Saves the gear library data asynchronously.
Initiates an asynchronous save operation for the current library state.
Definition at line 1377 of file GearLibrary.cpp.
shouldShowItem()
bool GearLibrary::shouldShowItem (const GearItem & item) const private
Determines if a gear item should be shown based on current search.
Parameters
item The gear item to check
Returns
true if the item should be shown
Checks search text to determine if an item should be visible in the current view. Uses fuzzy matching to ignore common separators and special characters.
Parameters
item The gear item to check
Returns
true if the item should be shown
Definition at line 271 of file GearLibrary.cpp.
References GearItem::categoryString, currentSearchText, GearItem::manufacturer, GearItem::name, normalizeForSearch(), and GearItem::tags.
Referenced by updateFilteredItems().
updateFilteredItems()
void GearLibrary::updateFilteredItems ()
Updates the filtered items in both list and tree views.
Refreshes the display of items based on current search criteria.
Definition at line 327 of file GearLibrary.cpp.
References cacheManager, GearTreeItem::Category, Compressor, currentSearchText, EQ, GearTreeItem::Favorites, GearTreeItem::Gear, gearItems, gearListBox, gearTreeView, GearTreeItem::Message, Other, Preamp, GearTreeItem::RecentlyUsed, refreshFavoritesSection(), refreshRecentlyUsedSection(), rootItem, and shouldShowItem().
Referenced by GearLibrary().
Member Data Documentation
cacheManager
CacheManager& GearLibrary::cacheManager private
Reference to the cache manager.
Definition at line 331 of file GearLibrary.h.
Referenced by addItem(), clearFavorites(), clearRecentlyUsed(), GearLibrary(), getCacheManager(), parseGearLibrary(), refreshFavoritesSection(), refreshRecentlyUsedSection(), and updateFilteredItems().
currentSearchText
juce::String GearLibrary::currentSearchText private
Current search text.
Definition at line 312 of file GearLibrary.h.
Referenced by GearLibrary(), shouldShowItem(), and updateFilteredItems().
fileSystem
IFileSystem& GearLibrary::fileSystem private
Reference to the file system.
Definition at line 330 of file GearLibrary.h.
Referenced by addItem(), GearLibrary(), and parseGearLibrary().
gearItems
juce::Array<GearItem> GearLibrary::gearItems private
Array of all gear items.
Definition at line 309 of file GearLibrary.h.
Referenced by addItem(), getGearItem(), getItems(), getNumRows(), paintListBoxItem(), parseGearLibrary(), refreshFavoritesSection(), refreshRecentlyUsedSection(), and updateFilteredItems().
gearListBox
std::unique_ptr<DraggableListBox> GearLibrary::gearListBox private
Legacy list box component.
Definition at line 302 of file GearLibrary.h.
Referenced by GearLibrary(), listBoxItemClicked(), resized(), and updateFilteredItems().
gearListModel
std::unique_ptr<GearListBoxModel> GearLibrary::gearListModel private
Model for the legacy list box.
Definition at line 301 of file GearLibrary.h.
Referenced by GearLibrary().
gearTreeView
std::unique_ptr<juce::TreeView> GearLibrary::gearTreeView private
Tree view for hierarchical display.
Definition at line 305 of file GearLibrary.h.
Referenced by GearLibrary(), refreshFavoritesSection(), refreshRecentlyUsedSection(), refreshTreeView(), resized(), updateFilteredItems(), and ~GearLibrary().
networkFetcher
INetworkFetcher& GearLibrary::networkFetcher private
Reference to the network fetcher.
Definition at line 329 of file GearLibrary.h.
Referenced by addItem(), GearLibrary(), loadGearItemsAsync(), and parseGearLibrary().
presetManager
PresetManager& GearLibrary::presetManager private
Reference to the preset manager.
Definition at line 332 of file GearLibrary.h.
Referenced by GearLibrary().
refreshButton
juce::DrawableButton GearLibrary::refreshButton {"RefreshButton", juce::DrawableButton::ButtonStyle::ImageOnButtonBackground} private
Button to refresh the gear list.
Definition at line 297 of file GearLibrary.h.
Referenced by buttonClicked(), GearLibrary(), and resized().
rootItem
std::unique_ptr<GearTreeItem> GearLibrary::rootItem private
Root item of the tree view.
Definition at line 306 of file GearLibrary.h.
Referenced by addItem(), GearLibrary(), parseGearLibrary(), refreshFavoritesSection(), refreshRecentlyUsedSection(), refreshTreeView(), and updateFilteredItems().
searchBox
juce::TextEditor GearLibrary::searchBox private
Text box for searching gear items.
Definition at line 298 of file GearLibrary.h.
Referenced by GearLibrary(), and resized().
titleLabel
juce::Label GearLibrary::titleLabel {"titleLabel", "Gear Library"} private
Title label for the library.
Definition at line 296 of file GearLibrary.h.
Referenced by GearLibrary(), and resized().
The documentation for this class was generated from the following files:
Source/GearLibrary.h
Source/GearLibrary.cpp