AnalogIQ: AnalogIQEditor Class Reference
AnalogIQEditor Class Reference
Main editor interface for the AnalogIQ plugin.
#include <AnalogIQEditor.h>
Classes
class FlatMenuButtonLookAndFeel
Custom LookAndFeel for menu buttons with no background or border.
class MenuBarContainer
Custom component for the menu bar container with styling.
Public Member Functions
AnalogIQEditor (AnalogIQProcessor &processor, IFileSystem &fileSystem, CacheManager &cacheManager, PresetManager &presetManager, GearLibrary &gearLibrary)
Constructs a new AnalogIQEditor.
AnalogIQEditor (AnalogIQProcessor &processor, CacheManager &cacheManager, PresetManager &presetManager, bool disableAutoLoad)
Constructs a new AnalogIQEditor for testing.
~AnalogIQEditor () override
Destructor for AnalogIQEditor.
void paint (juce::Graphics &) override
Paints the AnalogIQEditor component.
void resized () override
Handles resizing of the AnalogIQEditor component.
Rack * getRack () const
Gets a pointer to the rack component.
GearLibrary * getGearLibrary () const
Gets a pointer to the gear library component.
PresetManager & getPresetManager () const
Gets a reference to the preset manager.
Private Member Functions
void showPresetMenu ()
Shows the presets popup menu.
void showSavePresetDialog ()
Shows a dialog to save a new preset.
void showLoadPresetDialog ()
Shows a dialog to load a preset.
void showDeletePresetDialog ()
Shows a dialog to delete a preset.
void handleSavePreset (const juce::String &presetName)
Handles saving a preset with the given name.
void handleLoadPreset (const juce::String &presetName)
Handles loading a preset with the given name.
void performLoadPreset (const juce::String &presetName)
Performs the actual loading of a preset (called after confirmation if needed).
void handleDeletePreset (const juce::String &presetName)
Handles deleting a preset with the given name.
void refreshPresetMenu ()
Refreshes the preset menu with current preset list.
bool hasUnsavedChanges () const
Checks if the current rack state has unsaved changes.
void markAsModified ()
Marks the current state as having unsaved changes.
void clearModifiedState ()
Clears the modified state.
AnalogIQEditor (const AnalogIQEditor &)=delete
AnalogIQEditor & operator= (const AnalogIQEditor &)=delete
Private Attributes
AnalogIQProcessor & processor
IFileSystem & fileSystem
CacheManager & cacheManager
PresetManager & presetManager
GearLibrary & gearLibrary
juce::TabbedComponent mainTabs {juce::TabbedButtonBar::TabsAtTop}
Main tabbed interface.
std::unique_ptr< Rack > rack
Rack component.
std::unique_ptr< NotesPanel > notesPanel
Notes panel component.
juce::TextButton presetsMenuButton {"PresetsMenuButton"}
Menu button for preset operations.
bool isModified {false}
Tracks if the current state has unsaved changes.
juce::String currentPresetName
Name of the currently loaded preset, if any.
MenuBarContainer menuBarContainer
Container for the menu bar.
FlatMenuButtonLookAndFeel flatMenuLookAndFeel
Custom look and feel for menu buttons.
Detailed Description
Main editor interface for the AnalogIQ plugin.
The AnalogIQEditor class provides the user interface for the plugin, managing the gear library, rack, and notes panel. It supports drag and drop operations for gear items and organizes the interface using a tabbed layout.
Definition at line 30 of file AnalogIQEditor.h.
Constructor & Destructor Documentation
AnalogIQEditor() [1/3]
AnalogIQEditor::AnalogIQEditor (AnalogIQProcessor & processor, IFileSystem & fileSystem, CacheManager & cacheManager, PresetManager & presetManager, GearLibrary & gearLibrary)
Constructs a new AnalogIQEditor.
Parameters
processor Reference to the associated AudioProcessor
cacheManager Reference to the cache manager
presetManager Reference to the preset manager
Initializes the editor with a gear library, rack, and notes panel. Sets up the tabbed interface and configures drag and drop functionality.
Parameters
processor Reference to the associated AudioProcessor
fileSystem Reference to the file system
cacheManager Reference to the cache manager
presetManager Reference to the preset manager
gearLibrary Reference to the gear library
Definition at line 27 of file AnalogIQEditor.cpp.
References cacheManager, fileSystem, flatMenuLookAndFeel, gearLibrary, mainTabs, menuBarContainer, notesPanel, presetManager, presetsMenuButton, processor, rack, and showPresetMenu().
Referenced by AnalogIQEditor().
AnalogIQEditor() [2/3]
AnalogIQEditor::AnalogIQEditor (AnalogIQProcessor & processor, CacheManager & cacheManager, PresetManager & presetManager, bool disableAutoLoad)
Constructs a new AnalogIQEditor for testing.
Parameters
processor Reference to the associated AudioProcessor
cacheManager Reference to the cache manager
presetManager Reference to the preset manager
disableAutoLoad Whether to disable auto-loading of the gear library (for testing)
Initializes the editor with a gear library, rack, and notes panel. Sets up the tabbed interface and configures drag and drop functionality.
Parameters
processor Reference to the associated AudioProcessor
cacheManager Reference to the cache manager
presetManager Reference to the preset manager
disableAutoLoad Whether to disable auto-loading of the gear library (for testing)
Definition at line 111 of file AnalogIQEditor.cpp.
References cacheManager, fileSystem, flatMenuLookAndFeel, gearLibrary, getGearLibrary(), mainTabs, menuBarContainer, notesPanel, presetManager, presetsMenuButton, processor, rack, and showPresetMenu().
~AnalogIQEditor()
AnalogIQEditor::~AnalogIQEditor () override
Destructor for AnalogIQEditor.
Cleans up all components through unique_ptr automatic destruction.
Definition at line 182 of file AnalogIQEditor.cpp.
AnalogIQEditor() [3/3]
AnalogIQEditor::AnalogIQEditor (const AnalogIQEditor &) private delete
References AnalogIQEditor().
Member Function Documentation
clearModifiedState()
void AnalogIQEditor::clearModifiedState () private
Clears the modified state.
Definition at line 595 of file AnalogIQEditor.cpp.
References isModified.
Referenced by handleSavePreset(), and performLoadPreset().
getGearLibrary()
GearLibrary * AnalogIQEditor::getGearLibrary () const inline
Gets a pointer to the gear library component.
Returns
Pointer to the GearLibrary component
Definition at line 86 of file AnalogIQEditor.h.
References gearLibrary.
Referenced by AnalogIQEditor().
getPresetManager()
PresetManager & AnalogIQEditor::getPresetManager () const inline
Gets a reference to the preset manager.
Returns
Reference to the PresetManager instance
Definition at line 93 of file AnalogIQEditor.h.
References presetManager.
getRack()
Rack * AnalogIQEditor::getRack () const inline
Gets a pointer to the rack component.
Returns
Pointer to the Rack component
Definition at line 79 of file AnalogIQEditor.h.
References rack.
handleDeletePreset()
void AnalogIQEditor::handleDeletePreset (const juce::String & presetName) private
Handles deleting a preset with the given name.
Parameters
presetName The name of the preset to delete
Definition at line 549 of file AnalogIQEditor.cpp.
References currentPresetName, and presetManager.
Referenced by showDeletePresetDialog().
handleLoadPreset()
void AnalogIQEditor::handleLoadPreset (const juce::String & presetName) private
Handles loading a preset with the given name.
Parameters
presetName The name of the preset to load
Definition at line 506 of file AnalogIQEditor.cpp.
References performLoadPreset(), and rack.
Referenced by showLoadPresetDialog(), and showPresetMenu().
handleSavePreset()
void AnalogIQEditor::handleSavePreset (const juce::String & presetName) private
Handles saving a preset with the given name.
Parameters
presetName The name of the preset to save
Definition at line 483 of file AnalogIQEditor.cpp.
References clearModifiedState(), currentPresetName, presetManager, and rack.
Referenced by showSavePresetDialog().
hasUnsavedChanges()
bool AnalogIQEditor::hasUnsavedChanges () const private
Checks if the current rack state has unsaved changes.
Returns
true if there are unsaved changes, false otherwise
Definition at line 582 of file AnalogIQEditor.cpp.
References isModified.
markAsModified()
void AnalogIQEditor::markAsModified () private
Marks the current state as having unsaved changes.
Definition at line 587 of file AnalogIQEditor.cpp.
References isModified.
operator=()
AnalogIQEditor & AnalogIQEditor::operator= (const AnalogIQEditor &) private delete
paint()
void AnalogIQEditor::paint (juce::Graphics & g) override
Paints the AnalogIQEditor component.
Parameters
g The graphics context to paint with
Fills the background with the default window background color.
Parameters
g The graphics context to paint with
Definition at line 194 of file AnalogIQEditor.cpp.
performLoadPreset()
void AnalogIQEditor::performLoadPreset (const juce::String & presetName) private
Performs the actual loading of a preset (called after confirmation if needed).
Parameters
presetName The name of the preset to load
Definition at line 603 of file AnalogIQEditor.cpp.
References clearModifiedState(), currentPresetName, gearLibrary, presetManager, and rack.
Referenced by handleLoadPreset().
refreshPresetMenu()
void AnalogIQEditor::refreshPresetMenu () private
Refreshes the preset menu with current preset list.
Definition at line 575 of file AnalogIQEditor.cpp.
resized()
void AnalogIQEditor::resized () override
Handles resizing of the AnalogIQEditor component.
Arranges the menu bar at the top, gear library on the left side (1/4 width), and the tabbed interface (rack and notes) in the remaining space.
Definition at line 205 of file AnalogIQEditor.cpp.
References gearLibrary, mainTabs, menuBarContainer, and presetsMenuButton.
showDeletePresetDialog()
void AnalogIQEditor::showDeletePresetDialog () private
Shows a dialog to delete a preset.
Definition at line 411 of file AnalogIQEditor.cpp.
References handleDeletePreset(), and presetManager.
Referenced by showPresetMenu().
showLoadPresetDialog()
void AnalogIQEditor::showLoadPresetDialog () private
Shows a dialog to load a preset.
Definition at line 354 of file AnalogIQEditor.cpp.
References handleLoadPreset(), and presetManager.
Referenced by showPresetMenu().
showPresetMenu()
void AnalogIQEditor::showPresetMenu () private
Shows the presets popup menu.
Definition at line 224 of file AnalogIQEditor.cpp.
References handleLoadPreset(), presetManager, presetsMenuButton, showDeletePresetDialog(), showLoadPresetDialog(), and showSavePresetDialog().
Referenced by AnalogIQEditor(), and AnalogIQEditor().
showSavePresetDialog()
void AnalogIQEditor::showSavePresetDialog () private
Shows a dialog to save a new preset.
Definition at line 274 of file AnalogIQEditor.cpp.
References handleSavePreset(), and presetManager.
Referenced by showPresetMenu().
Member Data Documentation
cacheManager
CacheManager& AnalogIQEditor::cacheManager private
Definition at line 169 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), and AnalogIQEditor().
currentPresetName
juce::String AnalogIQEditor::currentPresetName private
Name of the currently loaded preset, if any.
Definition at line 183 of file AnalogIQEditor.h.
Referenced by handleDeletePreset(), handleSavePreset(), and performLoadPreset().
fileSystem
IFileSystem& AnalogIQEditor::fileSystem private
Definition at line 168 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), and AnalogIQEditor().
flatMenuLookAndFeel
FlatMenuButtonLookAndFeel AnalogIQEditor::flatMenuLookAndFeel private
Custom look and feel for menu buttons.
Definition at line 221 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), and AnalogIQEditor().
gearLibrary
GearLibrary& AnalogIQEditor::gearLibrary private
Definition at line 171 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), AnalogIQEditor(), getGearLibrary(), performLoadPreset(), and resized().
isModified
bool AnalogIQEditor::isModified {false} private
Tracks if the current state has unsaved changes.
Definition at line 182 of file AnalogIQEditor.h.
Referenced by clearModifiedState(), hasUnsavedChanges(), and markAsModified().
mainTabs
juce::TabbedComponent AnalogIQEditor::mainTabs {juce::TabbedButtonBar::TabsAtTop} private
Main tabbed interface.
Definition at line 174 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), AnalogIQEditor(), and resized().
menuBarContainer
MenuBarContainer AnalogIQEditor::menuBarContainer private
Container for the menu bar.
Definition at line 206 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), AnalogIQEditor(), and resized().
notesPanel
std::unique_ptr<NotesPanel> AnalogIQEditor::notesPanel private
Notes panel component.
Definition at line 176 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), and AnalogIQEditor().
presetManager
PresetManager& AnalogIQEditor::presetManager private
Definition at line 170 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), AnalogIQEditor(), getPresetManager(), handleDeletePreset(), handleSavePreset(), performLoadPreset(), showDeletePresetDialog(), showLoadPresetDialog(), showPresetMenu(), and showSavePresetDialog().
presetsMenuButton
juce::TextButton AnalogIQEditor::presetsMenuButton {"PresetsMenuButton"} private
Menu button for preset operations.
Definition at line 179 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), AnalogIQEditor(), resized(), and showPresetMenu().
processor
AnalogIQProcessor& AnalogIQEditor::processor private
Definition at line 167 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), and AnalogIQEditor().
rack
std::unique_ptr<Rack> AnalogIQEditor::rack private
Rack component.
Definition at line 175 of file AnalogIQEditor.h.
Referenced by AnalogIQEditor(), AnalogIQEditor(), getRack(), handleLoadPreset(), handleSavePreset(), and performLoadPreset().
The documentation for this class was generated from the following files:
Source/AnalogIQEditor.h
Source/AnalogIQEditor.cpp