AnalogIQ: RackSlot Class Reference
RackSlot Class Reference
Represents a slot in the rack that can contain a gear item.
#include <RackSlot.h>
Public Member Functions
RackSlot (int slotIndex)
Constructs a new RackSlot instance.
~RackSlot () override
Destructor for the RackSlot class.
void paint (juce::Graphics &g) override
Paints the rack slot and its contents.
void resized () override
Handles resizing of the rack slot component.
void buttonClicked (juce::Button *button) override
Handles button click events for the navigation buttons.
void updateButtonStates ()
Updates the enabled state of the navigation buttons.
void moveUp ()
Moves the gear item up one slot in the rack.
void moveDown ()
Moves the gear item down one slot in the rack.
void mouseDown (const juce::MouseEvent &e) override
Handles mouse down events on the rack slot.
void mouseDrag (const juce::MouseEvent &e) override
Handles mouse drag events on the rack slot.
void mouseUp (const juce::MouseEvent &e) override
Handles mouse up events on the rack slot.
void mouseDoubleClick (const juce::MouseEvent &e) override
Handles mouse double-click events on the rack slot.
bool isInterestedInDragSource (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Checks if the slot is interested in a drag source.
void itemDragEnter (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Handles when a dragged item enters the slot.
void itemDragMove (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Handles when a dragged item moves over the slot.
void itemDragExit (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Handles when a dragged item exits the slot.
void itemDropped (const juce::DragAndDropTarget::SourceDetails &dragSourceDetails) override
Handles when a dragged item is dropped onto the slot.
void setGearItem (GearItem *newGearItem)
Sets a new gear item in the slot.
void clearGearItem ()
Removes the current gear item from the slot.
GearItem * getGearItem () const
Gets the current gear item in the slot.
bool isAvailable () const
Checks if the slot is available (empty).
void setHighlighted (bool shouldHighlight)
Sets whether the slot should be highlighted.
int getIndex () const
Gets the index of this slot in the rack.
void createInstance ()
Creates a new instance of the current gear item.
void resetToSource ()
Resets an instance to its source gear item.
bool isInstance () const
Checks if the current gear item is an instance.
juce::String getInstanceId () const
Gets the instance ID of the current gear item.
Private Member Functions
void drawControls (juce::Graphics &g, const juce::Rectangle< int > &faceplateArea)
Draws all controls for the gear item.
void drawSwitch (juce::Graphics &g, const GearControl &control, int x, int y)
Draws a switch control.
void drawButton (juce::Graphics &g, const GearControl &control, int x, int y)
Draws a button control.
void drawFader (juce::Graphics &g, const GearControl &control, int x, int y)
Draws a fader control.
void drawKnob (juce::Graphics &g, const GearControl &control, int x, int y)
Draws a knob control.
GearControl * findControlAtPosition (const juce::Point< float > &position, const juce::Rectangle< int > &faceplateArea)
Finds a control at the specified position.
void handleSwitchInteraction (GearControl &control)
Handles interaction with a switch control.
void handleButtonInteraction (GearControl &control)
Handles interaction with a button control.
void handleFaderInteraction (GearControl &control, const juce::Point< float > &mousePos, const juce::Rectangle< int > &controlBounds)
Handles interaction with a fader control.
juce::Component * findParentRackComponent () const
Finds the parent Rack component.
RackSlot (const RackSlot &)=delete
RackSlot & operator= (const RackSlot &)=delete
Private Attributes
int index
The slot's position in the rack.
GearItem * gearItem = nullptr
The gear item in this slot, if any.
bool highlighted
Whether this slot is highlighted.
bool isDragging
Whether a drag operation is in progress.
float dragStartValue = 0.0f
Control value at drag start.
juce::Point< float > dragStartPos
Mouse position at drag start.
GearControl * activeControl = nullptr
Currently active control being manipulated.
float currentFaceplateScale = 1.0f
Current scale factor for faceplate rendering.
std::unique_ptr< juce::DrawableButton > upButton
Button for moving item up.
std::unique_ptr< juce::DrawableButton > downButton
Button for moving item down.
std::unique_ptr< juce::DrawableButton > removeButton
Button for removing item.
Detailed Description
Represents a slot in the rack that can contain a gear item.
The RackSlot class handles the visual representation and interaction with a single slot in the virtual rack. It manages gear items, their controls, and provides functionality for drag-and-drop operations, button interactions, and control manipulation.
Definition at line 28 of file RackSlot.h.
Constructor & Destructor Documentation
RackSlot() [1/2]
RackSlot::RackSlot (int slotIndex)
Constructs a new RackSlot instance.
Parameters
slotIndex The index of this slot in the rack
Initializes the slot with the given index, creates navigation buttons (up/down/remove), and sets up the component for user interaction.
Parameters
slotIndex The index of this slot in the rack
Definition at line 24 of file RackSlot.cpp.
References downButton, highlighted, index, isDragging, removeButton, upButton, and updateButtonStates().
Referenced by operator=().
~RackSlot()
RackSlot::~RackSlot () override
Destructor for the RackSlot class.
Cleans up resources and ensures all images are properly released.
Definition at line 109 of file RackSlot.cpp.
References downButton, gearItem, removeButton, and upButton.
RackSlot() [2/2]
RackSlot::RackSlot (const RackSlot &) private delete
Member Function Documentation
buttonClicked()
void RackSlot::buttonClicked (juce::Button * button) override
Handles button click events for the navigation buttons.
Parameters
button Pointer to the button that was clicked
Processes clicks on the up, down, and remove buttons to handle gear item movement and removal.
Parameters
button Pointer to the button that was clicked
Definition at line 669 of file RackSlot.cpp.
References clearGearItem(), downButton, moveDown(), moveUp(), removeButton, and upButton.
clearGearItem()
void RackSlot::clearGearItem ()
Removes the current gear item from the slot.
Clears the slot and updates the UI accordingly.
Definition at line 1460 of file RackSlot.cpp.
References findParentRackComponent(), gearItem, Rack::resized(), and updateButtonStates().
Referenced by buttonClicked(), and Rack::rearrangeGearAsSortableList().
createInstance()
void RackSlot::createInstance ()
Creates a new instance of the current gear item.
Converts the current gear item into an instance if it isn't already one.
Definition at line 1522 of file RackSlot.cpp.
References gearItem.
drawButton()
void RackSlot::drawButton (juce::Graphics & g, const GearControl & control, int x, int y) private
Draws a button control.
Parameters
g The graphics context to paint with
control The control to draw
x The x-coordinate for the control
y The y-coordinate for the control
Definition at line 377 of file RackSlot.cpp.
References GearControl::buttonFrames, GearControl::buttonSpriteSheet, currentFaceplateScale, GearControl::currentIndex, and GearControl::value.
Referenced by drawControls().
drawControls()
void RackSlot::drawControls (juce::Graphics & g, const juce::Rectangle< int > & faceplateArea) private
Draws all controls for the gear item.
Draws the controls for the gear item.
Parameters
g The graphics context to paint with
faceplateArea The area where the faceplate is drawn
Iterates through the gear item's controls and draws each one based on its type (switch, button, fader, or knob) at the appropriate position on the faceplate.
Parameters
g The graphics context to paint with
faceplateArea The area where the faceplate is drawn
Definition at line 251 of file RackSlot.cpp.
References GearControl::Button, drawButton(), drawFader(), drawKnob(), drawSwitch(), GearControl::Fader, gearItem, GearControl::Knob, and GearControl::Switch.
Referenced by paint().
drawFader()
void RackSlot::drawFader (juce::Graphics & g, const GearControl & control, int x, int y) private
Draws a fader control.
Parameters
g The graphics context to paint with
control The control to draw
x The x-coordinate for the control
y The y-coordinate for the control
Definition at line 471 of file RackSlot.cpp.
References currentFaceplateScale, GearControl::faderImage, GearControl::length, GearControl::orientation, and GearControl::value.
Referenced by drawControls().
drawKnob()
void RackSlot::drawKnob (juce::Graphics & g, const GearControl & control, int x, int y) private
Draws a knob control.
Parameters
g The graphics context to paint with
control The control to draw
x The x-coordinate for the control
y The y-coordinate for the control
Definition at line 569 of file RackSlot.cpp.
References currentFaceplateScale, GearControl::loadedImage, and GearControl::value.
Referenced by drawControls().
drawSwitch()
void RackSlot::drawSwitch (juce::Graphics & g, const GearControl & control, int x, int y) private
Draws a switch control.
Parameters
g The graphics context to paint with
control The control to draw
x The x-coordinate for the control
y The y-coordinate for the control
Definition at line 289 of file RackSlot.cpp.
References currentFaceplateScale, GearControl::currentIndex, GearControl::options, GearControl::orientation, GearControl::switchFrames, and GearControl::switchSpriteSheet.
Referenced by drawControls().
findControlAtPosition()
GearControl * RackSlot::findControlAtPosition (const juce::Point< float > & position, const juce::Rectangle< int > & faceplateArea) private
Finds a control at the specified position.
Parameters
position The position to check
faceplateArea The area where the faceplate is drawn
Returns
Pointer to the control at the position, or nullptr if none found
Searches through the gear item's controls to find one that contains the given position.
Parameters
position The position to check
faceplateArea The area where the faceplate is drawn
Returns
Pointer to the control at the position, or nullptr if none found
Definition at line 1075 of file RackSlot.cpp.
References GearControl::Button, currentFaceplateScale, GearControl::Fader, gearItem, GearControl::Knob, and GearControl::Switch.
Referenced by mouseDoubleClick(), and mouseDown().
findParentRackComponent()
juce::Component * RackSlot::findParentRackComponent () const private
Finds the parent Rack component.
Returns
Pointer to the parent Rack component, or nullptr if not found
Definition at line 1503 of file RackSlot.cpp.
Referenced by clearGearItem(), itemDropped(), moveDown(), moveUp(), and updateButtonStates().
getGearItem()
GearItem * RackSlot::getGearItem () const inline
Gets the current gear item in the slot.
Returns
Pointer to the current gear item, or nullptr if slot is empty
Definition at line 166 of file RackSlot.h.
References gearItem.
Referenced by Rack::fetchButtonSpriteSheet(), Rack::fetchFaceplateImage(), Rack::fetchFaderImage(), Rack::fetchKnobImage(), Rack::fetchSwitchSpriteSheet(), Rack::getSlotHeight(), Rack::itemDropped(), and Rack::rearrangeGearAsSortableList().
getIndex()
int RackSlot::getIndex () const inline
Gets the index of this slot in the rack.
Returns
The slot's index
Definition at line 189 of file RackSlot.h.
References index.
getInstanceId()
juce::String RackSlot::getInstanceId () const inline
Gets the instance ID of the current gear item.
Returns
The instance ID, or empty string if no gear item or not an instance
Definition at line 214 of file RackSlot.h.
References gearItem.
handleButtonInteraction()
void RackSlot::handleButtonInteraction (GearControl & control) private
Handles interaction with a button control.
Parameters
control The button control to handle
Updates the button's state when clicked, handling both momentary and latching button types.
Parameters
control The button control to handle
Definition at line 1225 of file RackSlot.cpp.
References GearControl::currentIndex, GearControl::momentary, GearControl::options, and GearControl::value.
Referenced by mouseDown(), and mouseDrag().
handleFaderInteraction()
void RackSlot::handleFaderInteraction (GearControl & control, const juce::Point< float > & mousePos, const juce::Rectangle< int > & controlBounds) private
Handles interaction with a fader control.
Parameters
control The fader control to handle
mousePos The current mouse position
controlBounds The bounds of the control
Updates the fader's value based on mouse position.
Parameters
control The fader control to handle
mousePos The current mouse position
controlBounds The bounds of the control
Definition at line 1250 of file RackSlot.cpp.
References GearControl::value.
handleSwitchInteraction()
void RackSlot::handleSwitchInteraction (GearControl & control) private
Handles interaction with a switch control.
Parameters
control The switch control to handle
Updates the switch's state when interacted with.
Parameters
control The switch control to handle
Definition at line 1210 of file RackSlot.cpp.
References GearControl::currentIndex, GearControl::options, and GearControl::value.
isAvailable()
bool RackSlot::isAvailable () const inline
Checks if the slot is available (empty).
Returns
true if the slot is empty
Definition at line 173 of file RackSlot.h.
References gearItem.
Referenced by Rack::getSlotHeight(), moveDown(), moveUp(), paint(), and updateButtonStates().
isInstance()
bool RackSlot::isInstance () const inline
Checks if the current gear item is an instance.
Returns
true if the current gear item is an instance
Definition at line 207 of file RackSlot.h.
References gearItem.
isInterestedInDragSource()
bool RackSlot::isInterestedInDragSource (const juce::DragAndDropTarget::SourceDetails & sourceDetails) override
Checks if the slot is interested in a drag source.
Parameters
dragSourceDetails Details about the drag source
Returns
true if the slot accepts drops from this source
Determines if the slot should accept drops from a particular drag source, such as the gear library.
Parameters
sourceDetails Details about the drag source
Returns
true if the slot accepts drops from this source
Definition at line 1266 of file RackSlot.cpp.
itemDragEnter()
void RackSlot::itemDragEnter (const juce::DragAndDropTarget::SourceDetails & dragSourceDetails) override
Handles when a dragged item enters the slot.
Parameters
dragSourceDetails Details about the drag source
Highlights the slot to indicate it can accept the drop.
Parameters
details Details about the drag source
Definition at line 1305 of file RackSlot.cpp.
References setHighlighted().
itemDragExit()
void RackSlot::itemDragExit (const juce::DragAndDropTarget::SourceDetails & dragSourceDetails) override
Handles when a dragged item exits the slot.
Parameters
dragSourceDetails Details about the drag source
Removes the highlight from the slot.
Parameters
details Details about the drag source
Definition at line 1327 of file RackSlot.cpp.
References setHighlighted().
itemDragMove()
void RackSlot::itemDragMove (const juce::DragAndDropTarget::SourceDetails & dragSourceDetails) override
Handles when a dragged item moves over the slot.
Parameters
dragSourceDetails Details about the drag source
details Details about the drag source
Definition at line 1315 of file RackSlot.cpp.
itemDropped()
void RackSlot::itemDropped (const juce::DragAndDropTarget::SourceDetails & details) override
Handles when a dragged item is dropped onto the slot.
Parameters
dragSourceDetails Details about the drag source and drop position
Processes the drop event and delegates to the parent rack to handle the actual gear item placement.
Parameters
details Details about the drag source and drop position
Definition at line 1340 of file RackSlot.cpp.
References findParentRackComponent(), Rack::itemDropped(), and setHighlighted().
mouseDoubleClick()
void RackSlot::mouseDoubleClick (const juce::MouseEvent & e) override
Handles mouse double-click events on the rack slot.
Parameters
e The mouse event details
Resets controls to their default values when double-clicked.
Parameters
e The mouse event details
Definition at line 1033 of file RackSlot.cpp.
References GearControl::Button, GearControl::Fader, findControlAtPosition(), gearItem, GearControl::Knob, and GearControl::Switch.
mouseDown()
void RackSlot::mouseDown (const juce::MouseEvent & e) override
Handles mouse down events on the rack slot.
Parameters
e The mouse event details
Processes mouse clicks on the slot and its controls, initiating drag operations for interactive controls.
Parameters
e The mouse event details
Definition at line 822 of file RackSlot.cpp.
References activeControl, GearControl::Button, dragStartPos, dragStartValue, GearControl::Fader, findControlAtPosition(), gearItem, handleButtonInteraction(), isDragging, GearControl::Knob, and GearControl::Switch.
mouseDrag()
void RackSlot::mouseDrag (const juce::MouseEvent & e) override
Handles mouse drag events on the rack slot.
Parameters
e The mouse event details
Updates control values based on drag position for interactive controls like faders, knobs, and switches.
Parameters
e The mouse event details
Definition at line 878 of file RackSlot.cpp.
References activeControl, GearControl::Button, currentFaceplateScale, dragStartPos, dragStartValue, GearControl::Fader, handleButtonInteraction(), isDragging, GearControl::Knob, and GearControl::Switch.
mouseUp()
void RackSlot::mouseUp (const juce::MouseEvent & e) override
Handles mouse up events on the rack slot.
Parameters
e The mouse event details
Finalizes drag operations and updates control values.
Parameters
e The mouse event details
Definition at line 1017 of file RackSlot.cpp.
References activeControl, and isDragging.
moveDown()
void RackSlot::moveDown ()
Moves the gear item down one slot in the rack.
Attempts to move the current gear item to the slot below this one. Only works if there is a gear item and this is not the last slot.
Definition at line 771 of file RackSlot.cpp.
References findParentRackComponent(), gearItem, Rack::getNumSlots(), index, isAvailable(), and Rack::rearrangeGearAsSortableList().
Referenced by buttonClicked().
moveUp()
void RackSlot::moveUp ()
Moves the gear item up one slot in the rack.
Attempts to move the current gear item to the slot above this one. Only works if there is a gear item and this is not the first slot.
Definition at line 726 of file RackSlot.cpp.
References findParentRackComponent(), gearItem, index, isAvailable(), and Rack::rearrangeGearAsSortableList().
Referenced by buttonClicked().
operator=()
RackSlot & RackSlot::operator= (const RackSlot &) private delete
References RackSlot().
paint()
void RackSlot::paint (juce::Graphics & g) override
Paints the rack slot and its contents.
Parameters
g The graphics context to paint with
Draws the slot background, border, and if a gear item is present, its faceplate image and controls. For empty slots, displays an "Empty Slot" message.
Parameters
g The graphics context to paint with
Definition at line 144 of file RackSlot.cpp.
References currentFaceplateScale, drawControls(), gearItem, highlighted, index, and isAvailable().
resetToSource()
void RackSlot::resetToSource ()
Resets an instance to its source gear item.
Restores the instance to match its source gear item's state.
Definition at line 1539 of file RackSlot.cpp.
References gearItem.
resized()
void RackSlot::resized () override
Handles resizing of the rack slot component.
Positions the navigation buttons (up/down/remove) in the top-right corner of the slot when the component is resized.
Definition at line 649 of file RackSlot.cpp.
References downButton, removeButton, and upButton.
setGearItem()
void RackSlot::setGearItem (GearItem * newGearItem)
Sets a new gear item in the slot.
Parameters
newGearItem Pointer to the new gear item to set
Updates the slot with a new gear item, preserving instance state if the current item is an instance.
Parameters
newGearItem Pointer to the new gear item to set
Definition at line 1402 of file RackSlot.cpp.
References GearItem::controls, GearItem::createInstance(), gearItem, GearItem::instanceId, GearItem::isInstance, GearItem::sourceUnitId, GearItem::unitId, and updateButtonStates().
Referenced by Rack::itemDropped(), and Rack::rearrangeGearAsSortableList().
setHighlighted()
void RackSlot::setHighlighted (bool shouldHighlight)
Sets whether the slot should be highlighted.
Parameters
shouldHighlight Whether the slot should be highlighted
Used to indicate when a slot is being dragged over or selected.
Parameters
shouldHighlight Whether the slot should be highlighted
Definition at line 1496 of file RackSlot.cpp.
References highlighted.
Referenced by itemDragEnter(), itemDragExit(), and itemDropped().
updateButtonStates()
void RackSlot::updateButtonStates ()
Updates the enabled state of the navigation buttons.
Enables/disables the up, down, and remove buttons based on the current state of the slot and its position in the rack.
Definition at line 691 of file RackSlot.cpp.
References downButton, findParentRackComponent(), gearItem, Rack::getNumSlots(), index, isAvailable(), removeButton, and upButton.
Referenced by clearGearItem(), RackSlot(), and setGearItem().
Member Data Documentation
activeControl
GearControl* RackSlot::activeControl = nullptr private
Currently active control being manipulated.
Definition at line 313 of file RackSlot.h.
Referenced by mouseDown(), mouseDrag(), and mouseUp().
currentFaceplateScale
float RackSlot::currentFaceplateScale = 1.0f private
Current scale factor for faceplate rendering.
Definition at line 314 of file RackSlot.h.
Referenced by drawButton(), drawFader(), drawKnob(), drawSwitch(), findControlAtPosition(), mouseDrag(), and paint().
downButton
std::unique_ptr<juce::DrawableButton> RackSlot::downButton private
Button for moving item down.
Definition at line 318 of file RackSlot.h.
Referenced by buttonClicked(), RackSlot(), resized(), updateButtonStates(), and ~RackSlot().
dragStartPos
juce::Point<float> RackSlot::dragStartPos private
Mouse position at drag start.
Definition at line 312 of file RackSlot.h.
Referenced by mouseDown(), and mouseDrag().
dragStartValue
float RackSlot::dragStartValue = 0.0f private
Control value at drag start.
Definition at line 311 of file RackSlot.h.
Referenced by mouseDown(), and mouseDrag().
gearItem
GearItem* RackSlot::gearItem = nullptr private
The gear item in this slot, if any.
Definition at line 308 of file RackSlot.h.
Referenced by clearGearItem(), createInstance(), drawControls(), findControlAtPosition(), getGearItem(), getInstanceId(), isAvailable(), isInstance(), mouseDoubleClick(), mouseDown(), moveDown(), moveUp(), paint(), resetToSource(), setGearItem(), updateButtonStates(), and ~RackSlot().
highlighted
bool RackSlot::highlighted private
Whether this slot is highlighted.
Definition at line 309 of file RackSlot.h.
Referenced by paint(), RackSlot(), and setHighlighted().
index
int RackSlot::index private
The slot's position in the rack.
Definition at line 307 of file RackSlot.h.
Referenced by getIndex(), moveDown(), moveUp(), paint(), RackSlot(), and updateButtonStates().
isDragging
bool RackSlot::isDragging private
Whether a drag operation is in progress.
Definition at line 310 of file RackSlot.h.
Referenced by mouseDown(), mouseDrag(), mouseUp(), and RackSlot().
removeButton
std::unique_ptr<juce::DrawableButton> RackSlot::removeButton private
Button for removing item.
Definition at line 319 of file RackSlot.h.
Referenced by buttonClicked(), RackSlot(), resized(), updateButtonStates(), and ~RackSlot().
upButton
std::unique_ptr<juce::DrawableButton> RackSlot::upButton private
Button for moving item up.
Definition at line 317 of file RackSlot.h.
Referenced by buttonClicked(), RackSlot(), resized(), updateButtonStates(), and ~RackSlot().
The documentation for this class was generated from the following files:
Source/RackSlot.h
Source/RackSlot.cpp