AnalogIQ: PresetManager Class Reference
PresetManager Class Reference
Manages preset operations for the Analogiq plugin.
#include <PresetManager.h>
Public Member Functions
PresetManager (IFileSystem &fileSystem, CacheManager &cacheManager)
Constructor for PresetManager.
~PresetManager ()=default
Destructor.
PresetManager (const PresetManager &)=delete
PresetManager & operator= (const PresetManager &)=delete
bool savePreset (const juce::String &name, Rack *rack)
Saves the current rack configuration as a preset.
bool loadPreset (const juce::String &name, Rack *rack, GearLibrary *gearLibrary)
Loads a preset into the rack.
bool deletePreset (const juce::String &name)
Deletes a preset file.
juce::StringArray getPresetNames () const
Gets a list of all available preset names.
juce::String getPresetsDirectory () const
Gets the presets directory.
bool isPresetValid (const juce::String &name) const
Checks if a preset exists and is valid.
juce::int64 getPresetTimestamp (const juce::String &name) const
Gets the creation timestamp of a preset.
juce::String getPresetDisplayName (const juce::String &name) const
Gets the display name for a preset (formatted with timestamp).
juce::String getPresetDisplayNameNoTimestamp (const juce::String &name) const
Gets the display name for a preset (without timestamp).
bool initializePresetsDirectory () const
Initializes the presets directory structure.
juce::String getLastErrorMessage () const
Gets the last error message.
void clearLastError ()
Clears the last error message.
bool validatePresetName (const juce::String &name, juce::String &errorMessage) const
Validates a preset name with detailed error reporting.
bool validatePresetFile (const juce::String &name, juce::String &errorMessage) const
Validates a preset file for corruption or format issues.
bool checkPresetNameConflict (const juce::String &name, juce::String &errorMessage) const
Checks if a preset name conflicts with existing presets.
juce::var getPresetInfo (const juce::String &name, juce::String &errorMessage) const
Gets detailed information about a preset.
Private Member Functions
juce::String nameToFilename (const juce::String &name) const
Converts a preset name to a safe filename.
juce::String filenameToName (const juce::String &filename) const
Converts a filename back to a preset name.
bool isValidPresetName (const juce::String &name) const
Validates a preset name.
juce::String serializeRackToJSON (Rack *rack) const
Serializes a rack configuration to JSON.
bool deserializeJSONToRack (const juce::String &jsonData, Rack *rack, GearLibrary *gearLibrary) const
Deserializes a JSON string to a rack configuration.
juce::String getPresetFile (const juce::String &name) const
Gets the preset file path for a given name.
Private Attributes
juce::String lastErrorMessage
Stores the last error message.
IFileSystem & fileSystem
Reference to the file system implementation.
CacheManager & cacheManager
Reference to the cache manager.
Detailed Description
Manages preset operations for the Analogiq plugin.
The PresetManager class handles saving and loading of complete rack configurations as presets. Each preset contains the ordered list of gear units, their instance states, and control values. Presets are stored as JSON files in the user's application data directory.
Definition at line 29 of file PresetManager.h.
Constructor & Destructor Documentation
PresetManager() [1/2]
PresetManager::PresetManager (IFileSystem & fileSystem, CacheManager & cacheManager)
Constructor for PresetManager.
Parameters
fileSystem Reference to the file system implementation
cacheManager Reference to the cache manager implementation
Definition at line 26 of file PresetManager.cpp.
References cacheManager, and fileSystem.
Referenced by operator=(), and PresetManager().
~PresetManager()
PresetManager::~PresetManager () default
Destructor.
PresetManager() [2/2]
PresetManager::PresetManager (const PresetManager &) delete
References PresetManager().
Member Function Documentation
checkPresetNameConflict()
bool PresetManager::checkPresetNameConflict (const juce::String & name, juce::String & errorMessage) const
Checks if a preset name conflicts with existing presets.
Parameters
name The preset name to check
errorMessage Output parameter for detailed error message
Returns
true if the name conflicts, false otherwise
Definition at line 795 of file PresetManager.cpp.
References getPresetNames().
Referenced by savePreset().
clearLastError()
void PresetManager::clearLastError ()
Clears the last error message.
Definition at line 649 of file PresetManager.cpp.
References lastErrorMessage.
Referenced by deletePreset(), loadPreset(), and savePreset().
deletePreset()
bool PresetManager::deletePreset (const juce::String & name)
Deletes a preset file.
Parameters
name The name of the preset to delete
Returns
true if the preset was deleted successfully, false otherwise
Definition at line 479 of file PresetManager.cpp.
References clearLastError(), fileSystem, getPresetFile(), and lastErrorMessage.
deserializeJSONToRack()
bool PresetManager::deserializeJSONToRack (const juce::String & jsonData, Rack * rack, GearLibrary * gearLibrary) const private
Deserializes a JSON string to a rack configuration.
Parameters
jsonData The JSON data to deserialize
rack Pointer to the rack to load into
gearLibrary Pointer to the gear library for unit lookup
Returns
true if deserialization was successful, false otherwise
Definition at line 208 of file PresetManager.cpp.
References GearControl::Button, cacheManager, GearItem::controls, Rack::fetchSchemaForGearItem(), fileSystem, INetworkFetcher::getDummy(), GearLibrary::getItems(), Rack::getNumSlots(), Rack::getSlot(), GearItem::instanceId, GearItem::isInstance, GearItem::sourceUnitId, and GearControl::Switch.
Referenced by loadPreset().
filenameToName()
juce::String PresetManager::filenameToName (const juce::String & filename) const private
Converts a filename back to a preset name.
Parameters
filename The filename to convert
Returns
The original preset name
Definition at line 93 of file PresetManager.cpp.
Referenced by getPresetNames().
getLastErrorMessage()
juce::String PresetManager::getLastErrorMessage () const
Gets the last error message.
Returns
The last error message, or empty string if no error
Definition at line 641 of file PresetManager.cpp.
References lastErrorMessage.
getPresetDisplayName()
juce::String PresetManager::getPresetDisplayName (const juce::String & name) const
Gets the display name for a preset (formatted with timestamp).
Parameters
name The name of the preset
Returns
The formatted display name
Definition at line 607 of file PresetManager.cpp.
References getPresetTimestamp().
getPresetDisplayNameNoTimestamp()
juce::String PresetManager::getPresetDisplayNameNoTimestamp (const juce::String & name) const
Gets the display name for a preset (without timestamp).
Parameters
name The name of the preset
Returns
The display name without timestamp
Definition at line 628 of file PresetManager.cpp.
getPresetFile()
juce::String PresetManager::getPresetFile (const juce::String & name) const private
Gets the preset file path for a given name.
Gets the preset file for a given name.
Parameters
name The preset name
Returns
The preset file path as a string
Parameters
name The preset name
Returns
The preset file
Definition at line 125 of file PresetManager.cpp.
References fileSystem, and nameToFilename().
Referenced by deletePreset(), getPresetInfo(), getPresetTimestamp(), isPresetValid(), loadPreset(), savePreset(), and validatePresetFile().
getPresetInfo()
juce::var PresetManager::getPresetInfo (const juce::String & name, juce::String & errorMessage) const
Gets detailed information about a preset.
Parameters
name The preset name
errorMessage Output parameter for error message if preset doesn't exist
Returns
A JSON object with preset details, or empty var if preset doesn't exist
Definition at line 826 of file PresetManager.cpp.
References fileSystem, and getPresetFile().
getPresetNames()
juce::StringArray PresetManager::getPresetNames () const
Gets a list of all available preset names.
Returns
Array of preset names
Definition at line 511 of file PresetManager.cpp.
References filenameToName(), and fileSystem.
Referenced by checkPresetNameConflict().
getPresetsDirectory()
juce::String PresetManager::getPresetsDirectory () const
Gets the presets directory.
Returns
The presets directory path as a string
The presets directory as a JUCE File object
Definition at line 36 of file PresetManager.cpp.
References fileSystem.
getPresetTimestamp()
juce::int64 PresetManager::getPresetTimestamp (const juce::String & name) const
Gets the creation timestamp of a preset.
Parameters
name The name of the preset
Returns
The timestamp as a 64-bit integer, or 0 if preset doesn't exist
Definition at line 567 of file PresetManager.cpp.
References fileSystem, and getPresetFile().
Referenced by getPresetDisplayName().
initializePresetsDirectory()
bool PresetManager::initializePresetsDirectory () const
Initializes the presets directory structure.
Creates the presets directory if it doesn't exist.
Returns
true if initialization was successful, false otherwise
Definition at line 50 of file PresetManager.cpp.
References fileSystem.
Referenced by savePreset().
isPresetValid()
bool PresetManager::isPresetValid (const juce::String & name) const
Checks if a preset exists and is valid.
Parameters
name The name of the preset to check
Returns
true if the preset exists and is valid, false otherwise
Definition at line 543 of file PresetManager.cpp.
References fileSystem, and getPresetFile().
isValidPresetName()
bool PresetManager::isValidPresetName (const juce::String & name) const private
Validates a preset name.
Parameters
name The preset name to validate
Returns
true if the name is valid, false otherwise
Definition at line 107 of file PresetManager.cpp.
loadPreset()
bool PresetManager::loadPreset (const juce::String & name, Rack * rack, GearLibrary * gearLibrary)
Loads a preset into the rack.
Parameters
name The name of the preset to load
rack Pointer to the rack to load into
gearLibrary Pointer to the gear library for unit lookup
Returns
true if the preset was loaded successfully, false otherwise
Definition at line 415 of file PresetManager.cpp.
References clearLastError(), deserializeJSONToRack(), fileSystem, getPresetFile(), lastErrorMessage, and validatePresetFile().
nameToFilename()
juce::String PresetManager::nameToFilename (const juce::String & name) const private
Converts a preset name to a safe filename.
Parameters
name The preset name to convert
Returns
A safe filename for the preset
Definition at line 72 of file PresetManager.cpp.
Referenced by getPresetFile().
operator=()
PresetManager & PresetManager::operator= (const PresetManager &) delete
References PresetManager().
savePreset()
bool PresetManager::savePreset (const juce::String & name, Rack * rack)
Saves the current rack configuration as a preset.
Parameters
name The name of the preset to save
rack Pointer to the rack to save
Returns
true if the preset was saved successfully, false otherwise
Definition at line 354 of file PresetManager.cpp.
References checkPresetNameConflict(), clearLastError(), fileSystem, getPresetFile(), initializePresetsDirectory(), lastErrorMessage, serializeRackToJSON(), and validatePresetName().
serializeRackToJSON()
juce::String PresetManager::serializeRackToJSON (Rack * rack) const private
Serializes a rack configuration to JSON.
Parameters
rack Pointer to the rack to serialize
Returns
JSON string representing the rack configuration
Definition at line 139 of file PresetManager.cpp.
References GearControl::Button, Rack::getNumSlots(), Rack::getSlot(), and GearControl::Switch.
Referenced by savePreset().
validatePresetFile()
bool PresetManager::validatePresetFile (const juce::String & name, juce::String & errorMessage) const
Validates a preset file for corruption or format issues.
Parameters
name The preset name to validate
errorMessage Output parameter for detailed error message
Returns
true if the preset is valid, false otherwise
Definition at line 719 of file PresetManager.cpp.
References fileSystem, and getPresetFile().
Referenced by loadPreset().
validatePresetName()
bool PresetManager::validatePresetName (const juce::String & name, juce::String & errorMessage) const
Validates a preset name with detailed error reporting.
Parameters
name The preset name to validate
errorMessage Output parameter for detailed error message
Returns
true if the name is valid, false otherwise
Definition at line 661 of file PresetManager.cpp.
Referenced by savePreset().
Member Data Documentation
cacheManager
CacheManager& PresetManager::cacheManager private
Reference to the cache manager.
Definition at line 185 of file PresetManager.h.
Referenced by deserializeJSONToRack(), and PresetManager().
fileSystem
IFileSystem& PresetManager::fileSystem private
Reference to the file system implementation.
Definition at line 184 of file PresetManager.h.
Referenced by deletePreset(), deserializeJSONToRack(), getPresetFile(), getPresetInfo(), getPresetNames(), getPresetsDirectory(), getPresetTimestamp(), initializePresetsDirectory(), isPresetValid(), loadPreset(), PresetManager(), savePreset(), and validatePresetFile().
lastErrorMessage
juce::String PresetManager::lastErrorMessage mutable private
Stores the last error message.
Definition at line 183 of file PresetManager.h.
Referenced by clearLastError(), deletePreset(), getLastErrorMessage(), loadPreset(), and savePreset().
The documentation for this class was generated from the following files:
Source/PresetManager.h
Source/PresetManager.cpp