AnalogIQ: AnalogIQProcessor Class Reference
AnalogIQProcessor Class Reference
Main audio processor for the AnalogIQ plugin.
#include <AnalogIQProcessor.h>
Public Member Functions
AnalogIQProcessor (INetworkFetcher &networkFetcher, IFileSystem &fileSystem)
Constructs a new AnalogIQProcessor.
~AnalogIQProcessor () override
Destructor for AnalogIQProcessor.
void prepareToPlay (double sampleRate, int samplesPerBlock) override
Prepares the processor for playback.
void releaseResources () override
Releases resources used by the processor.
bool isBusesLayoutSupported (const BusesLayout &layouts) const override
Checks if a bus layout is supported.
void processBlock (juce::AudioBuffer< float > &, juce::MidiBuffer &) override
Processes a block of audio data.
juce::AudioProcessorEditor * createEditor () override
Creates the plugin's editor.
bool hasEditor () const override
Checks if the plugin has an editor.
const juce::String getName () const override
Gets the name of the plugin.
bool acceptsMidi () const override
Checks if the plugin accepts MIDI input.
bool producesMidi () const override
Checks if the plugin produces MIDI output.
bool isMidiEffect () const override
Checks if the plugin is a MIDI effect.
double getTailLengthSeconds () const override
Gets the tail length in seconds.
int getNumPrograms () override
Gets the number of programs.
int getCurrentProgram () override
Gets the current program index.
void setCurrentProgram (int index) override
Sets the current program.
const juce::String getProgramName (int index) override
Gets the name of a program.
void changeProgramName (int index, const juce::String &newName) override
Changes the name of a program.
void getStateInformation (juce::MemoryBlock &destData) override
Saves the plugin's state.
void setStateInformation (const void *data, int sizeInBytes) override
Restores the plugin's state.
juce::AudioProcessorEditor * getActiveEditor ()
Gets the active editor.
juce::AudioProcessorValueTreeState & getState ()
Gets the processor's state tree.
INetworkFetcher & getNetworkFetcher ()
Gets the processor's network fetcher.
IFileSystem & getFileSystem ()
Gets the processor's file system.
CacheManager & getCacheManager ()
Gets the processor's cache manager.
PresetManager & getPresetManager ()
Gets the processor's preset manager.
GearLibrary & getGearLibrary ()
Gets the processor's gear library.
void saveInstanceState ()
Saves the current state of all gear instances.
void saveInstanceStateFromRack (Rack *rack, juce::ValueTree &instanceTree)
Saves the state of all gear instances from a rack.
void loadInstanceState ()
Loads the state of all gear instances.
void loadInstanceState (Rack *rack)
Loads the state of all gear instances from a rack.
void resetAllInstances ()
Resets all gear instances to their default state.
Private Member Functions
AnalogIQProcessor (const AnalogIQProcessor &)=delete
AnalogIQProcessor & operator= (const AnalogIQProcessor &)=delete
Private Attributes
juce::AudioProcessorValueTreeState state
The processor's state tree.
juce::UndoManager undoManager
Undo manager for state changes.
juce::AudioProcessorEditor * lastCreatedEditor = nullptr
Pointer to the last created editor (for testing)
Rack * rack = nullptr
Pointer to the rack (for testing)
INetworkFetcher & networkFetcher
Reference to the network fetcher for making HTTP requests.
std::unique_ptr< IFileSystem > fileSystem
std::unique_ptr< CacheManager > cacheManager
std::unique_ptr< PresetManager > presetManager
std::unique_ptr< GearLibrary > gearLibrary
Friends
class AnalogIQProcessorTests
Detailed Description
Main audio processor for the AnalogIQ plugin.
The AnalogIQProcessor class handles all audio processing and state management for the plugin. It provides a non-destructive audio pass-through while managing the state of gear instances and their settings.
Definition at line 30 of file AnalogIQProcessor.h.
Constructor & Destructor Documentation
AnalogIQProcessor() [1/2]
AnalogIQProcessor::AnalogIQProcessor (INetworkFetcher & networkFetcher, IFileSystem & fileSystem)
Constructs a new AnalogIQProcessor.
Parameters
networkFetcher Reference to the network fetcher to use
fileSystem Reference to the file system to use
Initializes the processor with stereo input and output buses, and sets up the state management system.
Parameters
networkFetcher Reference to the network fetcher to use
fileSystem Reference to the file system to use
Definition at line 24 of file AnalogIQProcessor.cpp.
References fileSystem, networkFetcher, state, and undoManager.
Referenced by AnalogIQProcessor().
~AnalogIQProcessor()
AnalogIQProcessor::~AnalogIQProcessor () override
Destructor for AnalogIQProcessor.
Definition at line 40 of file AnalogIQProcessor.cpp.
AnalogIQProcessor() [2/2]
AnalogIQProcessor::AnalogIQProcessor (const AnalogIQProcessor &) private delete
References AnalogIQProcessor().
Member Function Documentation
acceptsMidi()
bool AnalogIQProcessor::acceptsMidi () const override
Checks if the plugin accepts MIDI input.
Returns
false as this plugin does not process MIDI
Definition at line 59 of file AnalogIQProcessor.cpp.
changeProgramName()
void AnalogIQProcessor::changeProgramName (int index, const juce::String & newName) override
Changes the name of a program.
Parameters
index The program index
newName The new program name
index The program index (unused)
newName The new program name (unused)
Definition at line 141 of file AnalogIQProcessor.cpp.
createEditor()
juce::AudioProcessorEditor * AnalogIQProcessor::createEditor () override
Creates the plugin's editor.
Returns
A new AnalogIQEditor instance
Definition at line 214 of file AnalogIQProcessor.cpp.
References cacheManager, fileSystem, gearLibrary, lastCreatedEditor, presetManager, and rack.
getActiveEditor()
juce::AudioProcessorEditor * AnalogIQProcessor::getActiveEditor ()
Gets the active editor.
In a real plugin host, this is managed by JUCE. For testing purposes, we return the last created editor.
Returns
Pointer to the active editor, or nullptr if none exists
Definition at line 233 of file AnalogIQProcessor.cpp.
References lastCreatedEditor.
Referenced by loadInstanceState(), resetAllInstances(), and saveInstanceState().
getCacheManager()
CacheManager & AnalogIQProcessor::getCacheManager () inline
Gets the processor's cache manager.
Returns
Reference to the cache manager
Definition at line 214 of file AnalogIQProcessor.h.
References cacheManager.
getCurrentProgram()
int AnalogIQProcessor::getCurrentProgram () override
Gets the current program index.
Returns
0 as this plugin has no program support
Definition at line 109 of file AnalogIQProcessor.cpp.
getFileSystem()
IFileSystem & AnalogIQProcessor::getFileSystem () inline
Gets the processor's file system.
Returns
Reference to the file system
Definition at line 207 of file AnalogIQProcessor.h.
References fileSystem.
getGearLibrary()
GearLibrary & AnalogIQProcessor::getGearLibrary () inline
Gets the processor's gear library.
Returns
Reference to the gear library
Definition at line 228 of file AnalogIQProcessor.h.
References gearLibrary.
getName()
const juce::String AnalogIQProcessor::getName () const override
Gets the name of the plugin.
Returns
The plugin name
The plugin name as defined in JucePlugin_Name
Definition at line 49 of file AnalogIQProcessor.cpp.
getNetworkFetcher()
INetworkFetcher & AnalogIQProcessor::getNetworkFetcher () inline
Gets the processor's network fetcher.
Returns
Reference to the network fetcher
Definition at line 200 of file AnalogIQProcessor.h.
References networkFetcher.
getNumPrograms()
int AnalogIQProcessor::getNumPrograms () override
Gets the number of programs.
Returns
1 as this plugin has no program support
Definition at line 99 of file AnalogIQProcessor.cpp.
getPresetManager()
PresetManager & AnalogIQProcessor::getPresetManager () inline
Gets the processor's preset manager.
Returns
Reference to the preset manager
Definition at line 221 of file AnalogIQProcessor.h.
References presetManager.
getProgramName()
const juce::String AnalogIQProcessor::getProgramName (int index) override
Gets the name of a program.
Parameters
index The program index
Returns
Empty string as this plugin has no program support
Parameters
index The program index (unused)
Returns
Empty string as this plugin has no program support
Definition at line 130 of file AnalogIQProcessor.cpp.
getState()
juce::AudioProcessorValueTreeState & AnalogIQProcessor::getState () inline
Gets the processor's state tree.
Returns
Reference to the AudioProcessorValueTreeState
Definition at line 193 of file AnalogIQProcessor.h.
References state.
Referenced by getStateInformation(), and setStateInformation().
getStateInformation()
void AnalogIQProcessor::getStateInformation (juce::MemoryBlock & destData) override
Saves the plugin's state.
Parameters
destData The memory block to save the state to
Definition at line 243 of file AnalogIQProcessor.cpp.
References getState().
getTailLengthSeconds()
double AnalogIQProcessor::getTailLengthSeconds () const override
Gets the tail length in seconds.
Returns
0.0 as this plugin has no tail
Definition at line 89 of file AnalogIQProcessor.cpp.
hasEditor()
bool AnalogIQProcessor::hasEditor () const override
Checks if the plugin has an editor.
Returns
true as this plugin has an editor
Definition at line 204 of file AnalogIQProcessor.cpp.
isBusesLayoutSupported()
bool AnalogIQProcessor::isBusesLayoutSupported (const BusesLayout & layouts) const override
Checks if a bus layout is supported.
Parameters
layouts The bus layout to check
Returns
true if the layout is supported
Parameters
layouts The bus layout to check
Returns
true if the layout is supported (mono or stereo)
Definition at line 170 of file AnalogIQProcessor.cpp.
isMidiEffect()
bool AnalogIQProcessor::isMidiEffect () const override
Checks if the plugin is a MIDI effect.
Returns
false as this is not a MIDI effect
Definition at line 79 of file AnalogIQProcessor.cpp.
loadInstanceState() [1/2]
void AnalogIQProcessor::loadInstanceState ()
Loads the state of all gear instances.
Definition at line 446 of file AnalogIQProcessor.cpp.
References getActiveEditor(), loadInstanceState(), and rack.
Referenced by loadInstanceState().
loadInstanceState() [2/2]
void AnalogIQProcessor::loadInstanceState (Rack * rack)
Loads the state of all gear instances from a rack.
Loads the state of all gear instances.
Parameters
rack The rack containing the gear instances
Restores the state of each gear instance in the rack from the plugin's state tree, including control values and settings.
Definition at line 335 of file AnalogIQProcessor.cpp.
References cacheManager, GearItem::controls, EQ, fileSystem, GearControl::initialValue, GearControl::Knob, GearControl::name, networkFetcher, rack, Series500, state, GearControl::Switch, GearControl::type, and GearControl::value.
operator=()
AnalogIQProcessor & AnalogIQProcessor::operator= (const AnalogIQProcessor &) private delete
prepareToPlay()
void AnalogIQProcessor::prepareToPlay (double sampleRate, int samplesPerBlock) override
Prepares the processor for playback.
Parameters
sampleRate The sample rate
samplesPerBlock The block size
sampleRate The sample rate (unused)
samplesPerBlock The block size (unused)
Definition at line 152 of file AnalogIQProcessor.cpp.
processBlock()
void AnalogIQProcessor::processBlock (juce::AudioBuffer< float > & buffer, juce::MidiBuffer &) override
Processes a block of audio data.
Parameters
buffer The audio buffer to process
midiMessages The MIDI messages
buffer The audio buffer to process
midiMessages The MIDI messages (unused)
Definition at line 187 of file AnalogIQProcessor.cpp.
producesMidi()
bool AnalogIQProcessor::producesMidi () const override
Checks if the plugin produces MIDI output.
Returns
false as this plugin does not produce MIDI
Definition at line 69 of file AnalogIQProcessor.cpp.
releaseResources()
void AnalogIQProcessor::releaseResources () override
Releases resources used by the processor.
Definition at line 160 of file AnalogIQProcessor.cpp.
resetAllInstances()
void AnalogIQProcessor::resetAllInstances ()
Resets all gear instances to their default state.
Calls resetAllInstances() on the rack to restore all gear instances to their default settings.
Definition at line 463 of file AnalogIQProcessor.cpp.
References getActiveEditor(), and rack.
saveInstanceState()
void AnalogIQProcessor::saveInstanceState ()
Saves the current state of all gear instances.
Saves the state of each gear instance in the rack, including control values and settings, to the plugin's state tree.
Definition at line 271 of file AnalogIQProcessor.cpp.
References getActiveEditor(), rack, saveInstanceStateFromRack(), and state.
saveInstanceStateFromRack()
void AnalogIQProcessor::saveInstanceStateFromRack (Rack * rack, juce::ValueTree & instanceTree)
Saves the state of all gear instances from a rack.
Parameters
rack The rack containing the gear instances
instanceTree The value tree to save the state to
Definition at line 289 of file AnalogIQProcessor.cpp.
References rack, and GearControl::Switch.
Referenced by saveInstanceState().
setCurrentProgram()
void AnalogIQProcessor::setCurrentProgram (int index) override
Sets the current program.
Parameters
index The program index
index The program index (unused)
Definition at line 119 of file AnalogIQProcessor.cpp.
setStateInformation()
void AnalogIQProcessor::setStateInformation (const void * data, int sizeInBytes) override
Restores the plugin's state.
Parameters
data Pointer to the state data
sizeInBytes Size of the state data
Definition at line 256 of file AnalogIQProcessor.cpp.
References getState(), and state.
Friends And Related Symbol Documentation
AnalogIQProcessorTests
friend class AnalogIQProcessorTests friend
Definition at line 32 of file AnalogIQProcessor.h.
References AnalogIQProcessorTests, fileSystem, and networkFetcher.
Referenced by AnalogIQProcessorTests.
Member Data Documentation
cacheManager
std::unique_ptr<CacheManager> AnalogIQProcessor::cacheManager private
Definition at line 267 of file AnalogIQProcessor.h.
Referenced by createEditor(), getCacheManager(), and loadInstanceState().
fileSystem
std::unique_ptr<IFileSystem> AnalogIQProcessor::fileSystem private
Definition at line 266 of file AnalogIQProcessor.h.
Referenced by AnalogIQProcessor(), AnalogIQProcessorTests, createEditor(), getFileSystem(), and loadInstanceState().
gearLibrary
std::unique_ptr<GearLibrary> AnalogIQProcessor::gearLibrary private
Definition at line 269 of file AnalogIQProcessor.h.
Referenced by createEditor(), and getGearLibrary().
lastCreatedEditor
juce::AudioProcessorEditor* AnalogIQProcessor::lastCreatedEditor = nullptr private
Pointer to the last created editor (for testing)
Definition at line 263 of file AnalogIQProcessor.h.
Referenced by createEditor(), and getActiveEditor().
networkFetcher
INetworkFetcher& AnalogIQProcessor::networkFetcher private
Reference to the network fetcher for making HTTP requests.
Definition at line 265 of file AnalogIQProcessor.h.
Referenced by AnalogIQProcessor(), AnalogIQProcessorTests, getNetworkFetcher(), and loadInstanceState().
presetManager
std::unique_ptr<PresetManager> AnalogIQProcessor::presetManager private
Definition at line 268 of file AnalogIQProcessor.h.
Referenced by createEditor(), and getPresetManager().
rack
Rack* AnalogIQProcessor::rack = nullptr private
Pointer to the rack (for testing)
Definition at line 264 of file AnalogIQProcessor.h.
Referenced by createEditor(), loadInstanceState(), loadInstanceState(), resetAllInstances(), saveInstanceState(), and saveInstanceStateFromRack().
state
juce::AudioProcessorValueTreeState AnalogIQProcessor::state private
The processor's state tree.
Definition at line 261 of file AnalogIQProcessor.h.
Referenced by AnalogIQProcessor(), getState(), loadInstanceState(), saveInstanceState(), and setStateInformation().
undoManager
juce::UndoManager AnalogIQProcessor::undoManager private
Undo manager for state changes.
Definition at line 262 of file AnalogIQProcessor.h.
Referenced by AnalogIQProcessor().
The documentation for this class was generated from the following files:
Source/AnalogIQProcessor.h
Source/AnalogIQProcessor.cpp